
UPSMON_DOPATROLSRCH = compile preProcessFileLineNumbers "Common\Module\UPSMON\UPSMON\MODULES\ORDERS\UPSMON_PATROLSRCH\fnc\UPSMON_DOPATROLSRCH.sqf";
UPSMON_SrchPtrlFlankPos = compile preProcessFileLineNumbers "Common\Module\UPSMON\UPSMON\MODULES\ORDERS\UPSMON_PATROLSRCH\fnc\UPSMON_SrchPtrlFlankPos.sqf";
UPSMON_GETINPATROLSRCH = compile preProcessFileLineNumbers "Common\Module\UPSMON\UPSMON\MODULES\ORDERS\UPSMON_PATROLSRCH\fnc\UPSMON_GETINPATROLSRCH.sqf";
