//---TownNeighborsSystem

switch (toLower(worldName)) do {
	case "altis": {
		Selakano setVariable ["cti_town_neighbors",[Feres,ComPlatform]];
		Pyrgos setVariable ["cti_town_neighbors",[USSFREEDOM,Faronaki,Ekali,Dorida]];
		Dorida setVariable ["cti_town_neighbors",[Chalkeia,Pyrgos,Charkia,Limni]];
		Charkia setVariable ["cti_town_neighbors",[Rodopoli,Dorida,Anthrakia]];
		Kalochori setVariable ["cti_town_neighbors",[Paros]];
		Rodopoli setVariable ["cti_town_neighbors",[Kalithea,Paros,Charkia]];
		Paros setVariable ["cti_town_neighbors",[Rodopoli,Loannina,MilitaryOutpost,Limni,Kalochori]];
		Molos setVariable ["cti_town_neighbors",[Sofia,ResearchPlatform,MolosAirfield]];
		Anthrakia setVariable ["cti_town_neighbors",[Telos,Charkia,USSFREEDOM]];
		Telos setVariable ["cti_town_neighbors",[Military,Kalithea,Anthrakia]];
		Athira setVariable ["cti_town_neighbors",[Military,Ifestiona,Frini]];
		Koroni setVariable ["cti_town_neighbors",[Galati,Ifestiona,Lakka]];
		Galati setVariable ["cti_town_neighbors",[Koroni,Syrta,NorthAirfield]];
		Oreokastro setVariable ["cti_town_neighbors",[NorthAirfield,AgiosKonstantinos,TheDump]];
		Syrta setVariable ["cti_town_neighbors",[Kore,AgiosDionysios,Galati,TheDump]];
		AgiosDionysios setVariable ["cti_town_neighbors",[Lakka,Kore,Syrta,XirolimniDam]];
		Lakka setVariable ["cti_town_neighbors",[Neochori,AirBase,Koroni,AgiosDionysios]];
		Neochori setVariable ["cti_town_neighbors",[AirBase,Lakka,Military,USSFREEDOM,Poliakko]];
		XirolimniDam setVariable ["cti_town_neighbors",[AgiosDionysios,Zaros,Stadium,Poliakko]];
		Zaros setVariable ["cti_town_neighbors",[AACAirfield,Vikos,Panochori,XirolimniDam,Poliakko]];
		Kavala setVariable ["cti_town_neighbors",[Panochori,WindFarm,Stadium]];
		Poliakko setVariable ["cti_town_neighbors",[Zaros,XirolimniDam,Neochori,AACAirfield]];
		Airbase setVariable ["cti_town_neighbors",[Neochori,Lakka,Military,USSFREEDOM]];
		Military setVariable ["cti_town_neighbors",[Athira,Telos,Airbase]];
		Chalkeia setVariable ["cti_town_neighbors",[Dorida,Panagia,Limni]];
		Ifestiona setVariable ["cti_town_neighbors",[Koroni,Athira,Frini]];
		Negades setVariable ["cti_town_neighbors",[AgiosKonstantinos,Kore,Stadium]];
		Sofia setVariable ["cti_town_neighbors",[Molos,Nidasos,Loannina]];
		Panagia setVariable ["cti_town_neighbors",[Chalkeia,Feres,Ekali]];
		Kore setVariable ["cti_town_neighbors",[Syrta,AgiosDionysios,Negades]];
		SandAirfield setVariable ["cti_town_neighbors",[Loannina]];
		Makrynisi setVariable ["cti_town_neighbors",[Faronaki,AACAirfield]];
		Faronaki setVariable ["cti_town_neighbors",[Ekali,Vikos,Makrynisi,Pyrgos]];
		Kalithea setVariable ["cti_town_neighbors",[Rodopoli,Telos]];
		Vikos setVariable ["cti_town_neighbors",[Zaros,Faronaki,ComPlatform,OilRig]];
		Ekali setVariable ["cti_town_neighbors",[Panagia,Faronaki,ComPlatform,Pyrgos]];
		Frini setVariable ["cti_town_neighbors",[Ifestiona,Nychi,Athira,RadarPlatform]];
		Nychi setVariable ["cti_town_neighbors",[TheaterRuins,FuelDepot,Frini]];
		TheaterRuins setVariable ["cti_town_neighbors",[FuelDepot,MilitaryOutpost,Nychi]];
		MilitaryOutpost setVariable ["cti_town_neighbors",[TheaterRuins,Paros,HotelComplex]];
		NorthAirfield setVariable ["cti_town_neighbors",[Galati,Oreokastro,RadarPlatform]];
		Loannina setVariable ["cti_town_neighbors",[SandAirfield,Sofia,HotelComplex,Paros]];
		AACAirfield setVariable ["cti_town_neighbors",[Zaros,Makrynisi,Poliakko]];
		MolosAirfield setVariable ["cti_town_neighbors",[FuelDepot,Molos]];
		Panochori setVariable ["cti_town_neighbors",[Kavala,Stadium,Zaros,OilRig]];
		HotelComplex setVariable ["cti_town_neighbors",[MilitaryOutpost,Loannina,Nidasos]];
		Stadium setVariable ["cti_town_neighbors",[Negades,Kavala,Panochori,XirolimniDam]];
		Limni setVariable ["cti_town_neighbors",[Paros,Chalkeia,ResearchPlatform,Dorida]];
		AgiosKonstantinos setVariable ["cti_town_neighbors",[TheDump,Negades,Oreokastro,WindFarm]];
		Feres setVariable ["cti_town_neighbors",[Panagia,Selakano,ResearchPlatform]];
		Thedump setVariable ["cti_town_neighbors",[Oreokastro,Syrta,AgiosKonstantinos]];
		Nidasos setVariable ["cti_town_neighbors",[HotelComplex,Sofia]];
		USSFREEDOM setVariable ["cti_town_neighbors",[Neochori,Airbase,Anthrakia,Pyrgos]];
		ComPlatform setVariable ["cti_town_neighbors",[Ekali,Vikos,Selakano]];
		ResearchPlatform setVariable ["cti_town_neighbors",[Feres,Limni,Molos]];
		FuelDepot setVariable ["cti_town_neighbors",[RadarPlatform,Nychi,TheaterRuins,MolosAirfield]];
		OilRig setVariable ["cti_town_neighbors",[Vikos,Panochori]];
		RadarPlatform setVariable ["cti_town_neighbors",[NorthAirfield,Frini,FuelDepot]];
		WindFarm setVariable ["cti_town_neighbors",[AgiosKonstantinos,Kavala]];
	};
		case "isladuala3": {
		Camara setVariable ["cti_town_neighbors",[RamonsPlantation,VixenaFactory,CainnaWind]];
		RamonsPlantation setVariable ["cti_town_neighbors",[Camara,VixenaFactory]];
		VixenaFactory setVariable ["cti_town_neighbors",[RamonsPlantation,Camara]];
		CainnaWind setVariable ["cti_town_neighbors",[LinaPrison,Camara,Fishala,Kinsella]];
		LinaPrison setVariable ["cti_town_neighbors",[CainnaWind]];
		Fishala setVariable ["cti_town_neighbors",[CainnaWind]];
		Kinsella setVariable ["cti_town_neighbors",[CainnaWind,Orellan,AeroportoKinsella,Djolan,Numbo,DeBoor]];
		AeroportoKinsella setVariable ["cti_town_neighbors",[Kinsella,Orellan,RefugeeCamp,Numbo]];
		Orellan setVariable ["cti_town_neighbors",[Kinsella,AeroportoKinsella,Kingala]];
		Kingala setVariable ["cti_town_neighbors",[Orellan,Larenga]];
		Larenga setVariable ["cti_town_neighbors",[Kingala,RefugeeCamp,Mawimbela,AeroportoTasmera]];
		RefugeeCamp setVariable ["cti_town_neighbors",[AeroportoKinsella,Larenga,Numbo,Mawimbela]];
		AeroportoTasmera setVariable ["cti_town_neighbors",[Larenga,Ursana,Kimbaka]];
		Kimbaka setVariable ["cti_town_neighbors",[AeroportoTasmera,Boona]];
		Campolongo setVariable ["cti_town_neighbors",[Kirabo,Kimbaka,Boona,Lukasa]];
		Boona setVariable ["cti_town_neighbors",[Lukasa,Campolongo,Kimbaka]];
		Lukasa setVariable ["cti_town_neighbors",[Boona,Campolongo]];
		Kirabo setVariable ["cti_town_neighbors",[Campolongo,Ursana]];
		Ursana setVariable ["cti_town_neighbors",[Kirabo,Mawimbela,AeroportoTasmera,Cova]];
		Mawimbela setVariable ["cti_town_neighbors",[Cova,Ursana,Larenga,RefugeeCamp,Numbo]];
		Numbo setVariable ["cti_town_neighbors",[Kinsella,AeroportoKinsella,RefugeeCamp,Mawimbela,Naromaru]];
		Djolan setVariable ["cti_town_neighbors",[Kinsella,DeBoor,Vestinga,Papunya]];
		DeBoor setVariable ["cti_town_neighbors",[Kinsella,Djolan,Simbala]];
		Simbala setVariable ["cti_town_neighbors",[DeBoor,Spookdorp]];
		Katakabi setVariable ["cti_town_neighbors",[Spookdorp,Simbala]];
		Vestinga setVariable ["cti_town_neighbors",[Spookdorp,Djolan,Kwako]];
		Spookdorp setVariable ["cti_town_neighbors",[Vestinga,Katakabi,Simbala,Kwako]];
		Kwako setVariable ["cti_town_neighbors",[Caspal,Spookdorp,Vestinga,AeroportoSwonto,Forteza,Papunya]];
		AeroportoSwonto setVariable ["cti_town_neighbors",[Kwako,Swonto,Papunya,Bolabongo]];
		Swonto setVariable ["cti_town_neighbors",[AeroportoSwonto,Bolabongo,Engor,Caspal]];
		Caspal setVariable ["cti_town_neighbors",[Swonto,Forteza,PortoHazena,Kwako]];
		Forteza setVariable ["cti_town_neighbors",[Kwako,Caspal,PortoHazena,Minesini]];
		Minesini setVariable ["cti_town_neighbors",[Forteza,PortoHazena]];
		PortoHazena setVariable ["cti_town_neighbors",[Forteza,Minesini,Pinley,AshlakeResort,Caspal]];
		AshlakeResort setVariable ["cti_town_neighbors",[PortoHazena,Pinley]];
		Pinley setVariable ["cti_town_neighbors",[PortoHazena,AshlakeResort,Tarisol]];
		Tarisol setVariable ["cti_town_neighbors",[Pinley,Ravane]];
		Ravane setVariable ["cti_town_neighbors",[Tarisol,KalimboArmybase,DualaFireHQ]];
		KalimboArmybase setVariable ["cti_town_neighbors",[DualaFireHQ,Ravane,Mochiwo,Engor]];
		DualaFireHQ setVariable ["cti_town_neighbors",[Ravane,KalimboArmybase,Engor]];
		Mochiwo setVariable ["cti_town_neighbors",[KalimboArmybase,Polani]];
		Polani setVariable ["cti_town_neighbors",[Mochiwo,KieraYanga,Xibo]];
		KieraYanga setVariable ["cti_town_neighbors",[Polani,Kaalom,Mangomak,Xibo]];
		Mangomak setVariable ["cti_town_neighbors",[KieraYanga,Kaalom,Chaba,Xibo]];
		Chaba setVariable ["cti_town_neighbors",[Mangomak,Kaalom,MacHida,CampBokoro]];
		Kaalom setVariable ["cti_town_neighbors",[KieraYanga,Mangomak,MacHida,Chaba]];
		MacHida setVariable ["cti_town_neighbors",[Kaalom,Chaba]];
		CampBokoro setVariable ["cti_town_neighbors",[Chaba]];
		Xibo setVariable ["cti_town_neighbors",[Mangomak,KieraYanga,Casinda,Maluri,Zeelor,Polani]];
		Zeelor setVariable ["cti_town_neighbors",[Canto,Bobadah,Xibo]];
		Canto setVariable ["cti_town_neighbors",[Zeelor,Cova,AeroportoMolatia,Bobadah]];
		AeroportoMolatia setVariable ["cti_town_neighbors",[Canto,Bolabongo,Maluri,Pumado,Bolabongo,Naromaru,Cova,Bobadah]];
		Cova setVariable ["cti_town_neighbors",[Canto,Ursana,Mawimbela,Naromaru,AeroportoMolatia]];
		Maluri setVariable ["cti_town_neighbors",[Pumado,Xibo,Bobadah,AeroportoMolatia]];
		Pumado setVariable ["cti_town_neighbors",[AeroportoMolatia,Bolabongo,Engor,Casinda,Maluri]];
		Casinda setVariable ["cti_town_neighbors",[Pumado,Engor,Xibo]];
		Engor setVariable ["cti_town_neighbors",[Bolabongo,Swonto,DualaFireHQ,KalimboArmybase,Casinda,Pumado]];
		Bolabongo setVariable ["cti_town_neighbors",[Papunya,AeroportoSwonto,Swonto,Engor,Pumado,AeroportoMolatia,Naromaru]];
		Naromaru setVariable ["cti_town_neighbors",[Cova,Numbo,Papunya,Bolabongo,AeroportoMolatia]];
		Papunya setVariable ["cti_town_neighbors",[Djolan,Kwako,AeroportoSwonto,Bolabongo,Naromaru]];
		Bobadah setVariable ["cti_town_neighbors",[AeroportoMolatia,Maluri,Zeelor,Canto]];
		Imalia setVariable ["cti_town_neighbors",[Lukasa,Boona]];
	};
	case "stratis": {
		OutpostNorth setVariable ["cti_town_neighbors",[AgiaMarina,ComPlatform,KillFarm]];
		KillFarm setVariable ["cti_town_neighbors",[OutpostNorth,CampRogain,AgiaMarina]];
		AgiaMarina setVariable ["cti_town_neighbors",[OutpostNorth,KillFarm,StorageDump,TransmissionTowerBrit,AirBase,ComPlatform]];
		AirBase setVariable ["cti_town_neighbors",[ComPlatform,AgiaMarina,TransmissionTowerBrit,OysterBay,FuelDepot]];
		StorageDump setVariable ["cti_town_neighbors",[AgiaMarina,CampRogain,RadioControl,OldOutpost,TransmissionTowerBrit]];
		CampRogain setVariable ["cti_town_neighbors",[KillFarm,KaminoFiringRange,RadioControl,StorageDump]];
		RadioControl setVariable ["cti_town_neighbors",[StorageDump,CampRogain,KaminoFiringRange,LimeriBay,OldOutpost]];
		KaminoFiringRange setVariable ["cti_town_neighbors",[CampRogain,SubPen,RadioControl]];
		LimeriBay setVariable ["cti_town_neighbors",[RadioControl,SubPen,OldOutpost]];
		TransmissionTowerBrit setVariable ["cti_town_neighbors",[AgiaMarina,AirBase,StorageDump,OysterBay,OldOutpost]];
		OldOutpost setVariable ["cti_town_neighbors",[OysterBay,AirStationMike,StorageDump,RadioControl,TransmissionTowerBrit,LimeriBay]];
		CampTempest setVariable ["cti_town_neighbors",[OysterBay,Girna,FuelDepot,AirStationMike]];
		AirStationMike setVariable ["cti_town_neighbors",[OldOutpost,CampTempest,CampMaxwell,Tsoukalia]];
		OysterBay setVariable ["cti_town_neighbors",[AirBase,TransmissionTowerBrit,FuelDepot,CampTempest,OldOutpost]];
		Tsoukalia setVariable ["cti_town_neighbors",[AirStationMike,SubPen,CampMaxwell]];
		CampMaxwell setVariable ["cti_town_neighbors",[AirStationMike,LZConnor,Girna,Tsoukalia]];
		Girna setVariable ["cti_town_neighbors",[CampTempest,CampMaxwell,FuelDepot]];
		LZConnor setVariable ["cti_town_neighbors",[JayCove,CampMaxwell,SubPen]];
		JayCove setVariable ["cti_town_neighbors",[LZConnor,FuelDepot]];
		SubPen setVariable ["cti_town_neighbors",[LZConnor,Tsoukalia,LimeriBay,KaminoFiringRange]];
		ComPlatform setVariable ["cti_town_neighbors",[OutpostNorth,AirBase,AgiaMarina]];
		FuelDepot setVariable ["cti_town_neighbors",[CampTempest,Girna,OysterBay,JayCove,AirBase]];
	};
	case "tanoa": {
		Tuvanaka setVariable ["cti_town_neighbors", [TuvanakaAirbase,Belfort,IleDouen]];
		TuvanakaAirbase setVariable ["cti_town_neighbors", [Tuvanaka,CampRemnants]];
		Nani setVariable ["cti_town_neighbors", [Belfort,WindFarm,Sosovu,IleDouen]];
		Belfort setVariable ["cti_town_neighbors", [Tuvanaka,HarborRemnants,Nani]];
		HarborRemnants setVariable ["cti_town_neighbors", [Belfort,CampRemnants,OuaOueLumberyard]];
		CampRemnants setVariable ["cti_town_neighbors", [TuvanakaAirbase,HarborRemnants,lleSainteMarie]];
		WindFarm setVariable ["cti_town_neighbors", [Nani,Muaceba,IleDouen]];
		Sosovu setVariable ["cti_town_neighbors", [Muaceba,Regina,Nani]];
		Muaceba setVariable ["cti_town_neighbors", [WindFarm,Sosovu,Tavu,Balavu]];
		Tavu setVariable ["cti_town_neighbors", [Muaceba,Balavu,Laikoro]];
		Balavu setVariable ["cti_town_neighbors", [Muaceba,Tavu,Laikoro,Rautake]];
		Laikoro setVariable ["cti_town_neighbors", [Tavu,Balavu,Namuvaka]];
		Namuvaka setVariable ["cti_town_neighbors", [Laikoro,Rautake,Cerebu]];
		Rautake setVariable ["cti_town_neighbors", [Balavu,Namuvaka,Ferry]];
		Cerebu setVariable ["cti_town_neighbors", [Namuvaka,Yanukka]];
		Koumac setVariable ["cti_town_neighbors", [Lailai,Yanukka]];
		Yanukka setVariable ["cti_town_neighbors", [Lailai,Cerebu,Koumac]];
		Lailai setVariable ["cti_town_neighbors", [Katkoula,Yanukka,Koumac]];
		Ferry setVariable ["cti_town_neighbors", [Rautake,Katkoula]];
		Katkoula setVariable ["cti_town_neighbors", [Ferry,Savaka,Lailai]];
		Savaka setVariable ["cti_town_neighbors", [Katkoula,OilRig,Moddergat]];
		OilRig setVariable ["cti_town_neighbors", [Savaka,Moddergat,TuaduaIsland]];
		TuaduaIsland setVariable ["cti_town_neighbors", [OilRig,Blerick,USSFREEDOM]];
		Moddergat setVariable ["cti_town_neighbors", [Savaka,OilRig,Losi,Blerick]];
		Losi setVariable ["cti_town_neighbors", [Moddergat,Harcourt]];
		Harcourt setVariable ["cti_town_neighbors", [Doodstil,Losi,Kotomo]];
		Doodstil setVariable ["cti_town_neighbors", [PortBoise,Harcourt,FuelDepot]];
		PortBoise setVariable ["cti_town_neighbors", [Lijnhaven,Rereki,Doodstil]];
		Lijnhaven setVariable ["cti_town_neighbors", [Blerick,PortBoise,Rereki]];
		Rereki setVariable ["cti_town_neighbors", [Lijnhaven,PortBoise,USSFREEDOM]];
		Blerick setVariable ["cti_town_neighbors", [TuaduaIsland,Moddergat,Lijnhaven]];
		FuelDepot setVariable ["cti_town_neighbors", [Doodstil,Oumere,ComPlatform,USSFREEDOM]];
		lleSainteMarie setVariable ["cti_town_neighbors", [CampRemnants,CoralReef]];
		CoralReef setVariable ["cti_town_neighbors", [lleSainteMarie,TikiHotel,SaintPaul]];
		TikiHotel setVariable ["cti_town_neighbors", [CoralReef,HotelResort]];
		HotelResort setVariable ["cti_town_neighbors", [TikiHotel,Aerodrome,ComPlatform]];
		OuaOueLumberyard setVariable ["cti_town_neighbors", [HarborRemnants,Nicolet,Georgetown]];
		Nicolet setVariable ["cti_town_neighbors", [OuaOueLumberyard,SaintPaul]];
		SaintPaul setVariable ["cti_town_neighbors", [CoralReef,Nicolet,LaRochelle,Galili]];
		LaRochelle setVariable ["cti_town_neighbors", [SaintPaul,Aerodrome,CommsAlpha]];
		Aerodrome setVariable ["cti_town_neighbors", [HotelResort,LaRochelle,IndustrialPort]];
		IndustrialPort setVariable ["cti_town_neighbors", [Aerodrome,Vatukoulo,CommsBravo,ComPlatform]];
		Galili setVariable ["cti_town_neighbors", [SaintPaul,CommsAlpha,Tanouka]];
		CommsAlpha setVariable ["cti_town_neighbors", [LaRochelle,CommsBravo,Galili]];
		CommsBravo setVariable ["cti_town_neighbors", [CommsAlpha,Vagalala,IndustrialPort]];
		Vatukoulo setVariable ["cti_town_neighbors", [IndustrialPort,Luganville,Vagalala]];
		Georgetown setVariable ["cti_town_neighbors", [OuaOueLumberyard,TempleOfDeath,Regina]];
		TempleOfDeath setVariable ["cti_town_neighbors", [Georgetown,Tanouka]];
		Tanouka setVariable ["cti_town_neighbors", [Galili,TempleOfDeath,Vagalala,AeroportdeTanoa]];
		Vagalala setVariable ["cti_town_neighbors", [Vatukoulo,CommsBravo,Tanouka,Lakatoro,BloodRuins]];
		Regina setVariable ["cti_town_neighbors", [Georgetown,Sosovu,AeroportdeTanoa]];
		AeroportdeTanoa setVariable ["cti_town_neighbors", [Regina,Tanouka,Lumberyard]];
		Lakatoro setVariable ["cti_town_neighbors", [Lumberyard,Vagalala]];
		Lumberyard setVariable ["cti_town_neighbors", [AeroportdeTanoa,Lakatoro,BloodRuins,Kotomo]];
		BloodRuins setVariable ["cti_town_neighbors", [Lumberyard,Oumere,Vagalala]];
		Kotomo setVariable ["cti_town_neighbors", [Harcourt,Lumberyard,Oumere]];
		Oumere setVariable ["cti_town_neighbors", [FuelDepot,Kotomo,BloodRuins,Luganville]];
		Luganville setVariable ["cti_town_neighbors", [Vatukoulo,Oumere]];
		IleDouen setVariable ["cti_town_neighbors", [Tuvanaka,Nani,WindFarm]];
		ComPlatform setVariable ["cti_town_neighbors", [IndustrialPort,HotelResort,FuelDepot]];
		USSFREEDOM setVariable ["cti_town_neighbors", [FuelDepot,Rereki,TuaduaIsland]];
	};
	case "malden": {
		Moray setVariable ["cti_town_neighbors",[ComPlatform,WindFarm]];
		ComPlatform setVariable ["cti_town_neighbors",[Moray,Lolisse,Goisse]];
		Lolisse setVariable ["cti_town_neighbors",[ComPlatform,Goisse,AbandonedBase,LesSablesBay]];
		AbandonedBase setVariable ["cti_town_neighbors",[Lolisse,LesSablesBay,MountChauve,MilitaryBase,RadioStation]];
		LesSablesBay setVariable ["cti_town_neighbors",[Lolisse,AbandonedBase,SubPen]];
		MilitaryBase setVariable ["cti_town_neighbors",[AbandonedBase,RadioStation,Airport]];
		RadioStation setVariable ["cti_town_neighbors",[AbandonedBase,MilitaryBase,SaintLouis]];
		Airport setVariable ["cti_town_neighbors",[MilitaryBase,SubPen,SaintLouis]];
		SubPen setVariable ["cti_town_neighbors",[Airport,LesSablesBay,OilRig]];
		SaintLouis setVariable ["cti_town_neighbors",[RadioStation,Airport,LaTrinite,Larche]];
		Larche setVariable ["cti_town_neighbors",[SaintLouis,MountChauve,LaTrinite]];
		LaTrinite setVariable ["cti_town_neighbors",[SaintLouis,Larche,Dourdan,LeRoi]];
		LeRoi setVariable ["cti_town_neighbors",[LaTrinite]];
		Dourdan setVariable ["cti_town_neighbors",[Arudy,Houdan,LaTrinite]];
		MountChauve setVariable ["cti_town_neighbors",[AbandonedBase,Larche,SaintJean]];
		SaintJean setVariable ["cti_town_neighbors",[MountChauve,PicDeFeas,Goisse]];
		Goisse setVariable ["cti_town_neighbors",[ComPlatform,Lolisse,SaintJean,WindFarm]];
		Arudy setVariable ["cti_town_neighbors",[PicDeFeas,Dourdan]];
		PicDeFeas setVariable ["cti_town_neighbors",[SaintJean,Arudy,LaPessagne]];
		LaPessagne setVariable ["cti_town_neighbors",[PicDeFeas,Carton,Arette]];
		WindFarm setVariable ["cti_town_neighbors",[Moray,Goisse,Arette,Faro]];
		Arette setVariable ["cti_town_neighbors",[WindFarm,Ridge,LaPessagne]];
		Ridge setVariable ["cti_town_neighbors",[Carton,Faro,Arette,LaRiviere]];
		Faro setVariable ["cti_town_neighbors",[WindFarm,Ridge,Lighthouse]];
		Carton setVariable ["cti_town_neighbors",[LaPessagne,Ridge,LaRiviere,Dorres]];
		LaRiviere setVariable ["cti_town_neighbors",[Carton,Cancon,Ridge,Dorres]];
		Dorres setVariable ["cti_town_neighbors",[Carton,LaRiviere,Cancon,Chapoi,DentsBowl]];
		Cancon setVariable ["cti_town_neighbors",[LaRiviere,Dorres,Lighthouse,BaieduNain,Chapoi]];
		Chapoi setVariable ["cti_town_neighbors",[Cancon,Dorres,BaieduNain,HarborTown]];
		Lighthouse setVariable ["cti_town_neighbors",[Faro,Cancon,FuelDepot]];
		BaieduNain setVariable ["cti_town_neighbors",[Cancon,FuelDepot,Chapoi,LePort]];
		Houdan setVariable ["cti_town_neighbors",[HarborTown,DentsBowl,Dourdan,GolfeLighthouse]];
		DentsBowl setVariable ["cti_town_neighbors",[Dorres,Houdan]];
		GolfeLighthouse setVariable ["cti_town_neighbors",[ParadiseLighthouse,Houdan,HarborTown]];
		HarborTown setVariable ["cti_town_neighbors",[Chapoi,LePort,MilitaryHarbor,Houdan,GolfeLighthouse]];
		LePort setVariable ["cti_town_neighbors",[BaieduNain,HarborTown,FuelDepot,MilitaryHarbor]];
		FuelDepot setVariable ["cti_town_neighbors",[Lighthouse,BaieduNain,LePort,MilLighthouse]];
		MilitaryHarbor setVariable ["cti_town_neighbors",[LePort,HarborTown,MilLighthouse,ParadiseLighthouse]];
		MilLighthouse setVariable ["cti_town_neighbors",[FuelDepot,MilitaryHarbor,ParadiseLighthouse,OilRig]];
		ParadiseLighthouse setVariable ["cti_town_neighbors",[GolfeLighthouse,MilLighthouse,OilRig,MilitaryHarbor]];
		OilRig setVariable ["cti_town_neighbors",[ParadiseLighthouse,SubPen,MilLighthouse]];
	};	
	case "chernarus": {
		Kamenka setVariable ["cti_town_neighbors", [Pavlovo, Komarovo]];
		Komarovo setVariable ["cti_town_neighbors", [Bor, Balota, Kamenka]];
		Balota setVariable ["cti_town_neighbors", [Kozlovka, Komarovo, Chernogorsk]];
		Chernogorsk setVariable ["cti_town_neighbors", [Balota, Nadezhdino, Prigorodki, Kozlovka, Mogilevka, FuelDepot]];
		Prigorodki setVariable ["cti_town_neighbors", [Chernogorsk, Elektrozavodsk, Pusta]];
		Elektrozavodsk setVariable ["cti_town_neighbors", [Prigorodki, Pusta, Kamyshovo, Staroye, WindFarm, FuelDepot]];
		Kamyshovo setVariable ["cti_town_neighbors", [Elektrozavodsk, Msta, Tulga]];
		Solnichniy setVariable ["cti_town_neighbors", [Msta, Nizhnoye, Dolina, Orlovets, Tulga, USSWasp]];
		Nizhnoye setVariable ["cti_town_neighbors", [Solnichniy, Berezino, USSWasp, Orlovets]];
		Berezino setVariable ["cti_town_neighbors", [Nizhnoye, Khelm, Orlovets, Dubrovka]];
		Khelm setVariable ["cti_town_neighbors", [Berezino, Krasnostav, Olsha, Dubrovka]];
		Krasnostav setVariable ["cti_town_neighbors", [Olsha, Gvozdno, Dubrovka, Khelm, Hill366]];
		Olsha setVariable ["cti_town_neighbors", [Krasnostav, Khelm,USSWasp]];
		Gvozdno setVariable ["cti_town_neighbors", [Krasnostav, Grishino, Dubrovka, Hill366, Altar, DevilsCastle]];
		Grishino setVariable ["cti_town_neighbors", [Gvozdno, Petrovka, Kabanino, AirField, Altar, DevilsCastle]];
		Petrovka setVariable ["cti_town_neighbors", [Grishino, Lopatino, Airfield, DevilsCastle, Hill366]];
		Lopatino setVariable ["cti_town_neighbors", [Petrovka, Vybor, Pustoshka, Airfield]];
		Myshkino setVariable ["cti_town_neighbors", [Zelenogorsk, Pustoshka]];
		Zelenogorsk setVariable ["cti_town_neighbors", [Myshkino, Pogorevka, Kozlovka, Pavlovo, Bor]];
		Pavlovo setVariable ["cti_town_neighbors", [Kamenka, Zelenogorsk, Bor]];
		Kozlovka setVariable ["cti_town_neighbors", [Zelenogorsk, Nadezhdino, Chernogorsk, Balota, Pogorevka, Bor]];
		Nadezhdino setVariable ["cti_town_neighbors", [Kozlovka, Chernogorsk, Mogilevka, Vyshnoye]];
		Mogilevka setVariable ["cti_town_neighbors", [Vyshnoye, Pusta, Nadezhdino, Staroye, Chernogorsk]];
		Pusta setVariable ["cti_town_neighbors", [Mogilevka, Elektrozavodsk, Prigorodki, Staroye]];
		Staroye setVariable ["cti_town_neighbors", [Shakhovka, Guglovo, Elektrozavodsk, Msta, Mogilevka, Pusta, Dolina]];
		Msta setVariable ["cti_town_neighbors", [Staroye, Kamyshovo, Solnichniy, Dolina, Tulga]];
		Dolina setVariable ["cti_town_neighbors", [Staroye, Solnichniy, Shakhovka, Polana, Msta, Orlovets]];
		Orlovets setVariable ["cti_town_neighbors", [Nizhnoye, Polana, Dolina, Solnichniy]];
		Polana setVariable ["cti_town_neighbors", [Orlovets, Dolina, Shakhovka, Gorka]];
		Gorka setVariable ["cti_town_neighbors", [Dubrovka, Polana, Guglovo, Altar]];
		Dubrovka setVariable ["cti_town_neighbors", [Gorka, Krasnostav, Berezino, Khelm, Altar, Gvozdno]];
		Shakhovka setVariable ["cti_town_neighbors", [Staroye, Polana, Dolina, Guglovo]];
		Guglovo setVariable ["cti_town_neighbors", [Staroye, NovySobor, Shakhovka, Vyshnoye, Gorka]];
		Vyshnoye setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Mogilevka, Nadezhdino, Pogorevka]];
		StarySobor setVariable ["cti_town_neighbors", [Vyshnoye, Kabanino, Pogorevka, NovySobor]];
		Pogorevka setVariable ["cti_town_neighbors", [Zelenogorsk, StarySobor, Vyshnoye, Pustoshka, Kozlovka, Vybor, Kabanino]];
		Kabanino setVariable ["cti_town_neighbors", [Vybor, Grishino, StarySobor, Pogorevka, Airfield]];
		Vybor setVariable ["cti_town_neighbors", [Kabanino, Lopatino, Pustoshka, Pogorevka, Airfield]];
		Pustoshka setVariable ["cti_town_neighbors", [Vybor, Myshkino, Lopatino, Pogorevka]];
		Hill366 setVariable ["cti_town_neighbors", [Gvozdno, Krasnostav, DevilsCastle, Petrovka]];
		Airfield setVariable ["cti_town_neighbors", [Vybor, Lopatino, Kabanino, Petrovka, Grishino]];
		Tulga setVariable ["cti_town_neighbors", [Solnichniy, Kamyshovo, Msta]];
		Altar setVariable ["cti_town_neighbors", [NovySobor, Gorka, Gvozdno, Grishino]];
		DevilsCastle setVariable ["cti_town_neighbors", [Grishino, Gvozdno, Petrovka, Hill366]];
		NovySobor setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Altar]];
		WindFarm setVariable ["cti_town_neighbors", [Elektrozavodsk, USSWasp, FuelDepot]];
		FuelDepot setVariable ["cti_town_neighbors", [Chernogorsk, WindFarm, Elektrozavodsk]];
		USSWasp setVariable ["cti_town_neighbors", [Solnichniy, Nizhnoye, WindFarm, Olsha]];
		Bor setVariable ["cti_town_neighbors", [Zelenogorsk, Kozlovka, Pavlovo, Komarovo]];

	};
	case "chernarus_summer": {
		Kamenka setVariable ["cti_town_neighbors", [Pavlovo, Komarovo]];
		Komarovo setVariable ["cti_town_neighbors", [Bor, Balota, Kamenka]];
		Balota setVariable ["cti_town_neighbors", [Kozlovka, Komarovo, Chernogorsk]];
		Chernogorsk setVariable ["cti_town_neighbors", [Balota, Nadezhdino, Prigorodki, Kozlovka, Mogilevka, FuelDepot]];
		Prigorodki setVariable ["cti_town_neighbors", [Chernogorsk, Elektrozavodsk, Pusta]];
		Elektrozavodsk setVariable ["cti_town_neighbors", [Prigorodki, Pusta, Kamyshovo, Staroye, WindFarm, FuelDepot]];
		Kamyshovo setVariable ["cti_town_neighbors", [Elektrozavodsk, Msta, Tulga]];
		Solnichniy setVariable ["cti_town_neighbors", [Msta, Nizhnoye, Dolina, Orlovets, Tulga, USSWasp]];
		Nizhnoye setVariable ["cti_town_neighbors", [Solnichniy, Berezino, USSWasp, Orlovets]];
		Berezino setVariable ["cti_town_neighbors", [Nizhnoye, Khelm, Orlovets, Dubrovka]];
		Khelm setVariable ["cti_town_neighbors", [Berezino, Krasnostav, Olsha, Dubrovka]];
		Krasnostav setVariable ["cti_town_neighbors", [Olsha, Gvozdno, Dubrovka, Khelm, Hill366]];
		Olsha setVariable ["cti_town_neighbors", [Krasnostav, Khelm,USSWasp]];
		Gvozdno setVariable ["cti_town_neighbors", [Krasnostav, Grishino, Dubrovka, Hill366, Altar, DevilsCastle]];
		Grishino setVariable ["cti_town_neighbors", [Gvozdno, Petrovka, Kabanino, AirField, Altar, DevilsCastle]];
		Petrovka setVariable ["cti_town_neighbors", [Grishino, Lopatino, Airfield, DevilsCastle, Hill366]];
		Lopatino setVariable ["cti_town_neighbors", [Petrovka, Vybor, Pustoshka, Airfield]];
		Myshkino setVariable ["cti_town_neighbors", [Zelenogorsk, Pustoshka]];
		Zelenogorsk setVariable ["cti_town_neighbors", [Myshkino, Pogorevka, Kozlovka, Pavlovo, Bor]];
		Pavlovo setVariable ["cti_town_neighbors", [Kamenka, Zelenogorsk, Bor]];
		Kozlovka setVariable ["cti_town_neighbors", [Zelenogorsk, Nadezhdino, Chernogorsk, Balota, Pogorevka, Bor]];
		Nadezhdino setVariable ["cti_town_neighbors", [Kozlovka, Chernogorsk, Mogilevka, Vyshnoye]];
		Mogilevka setVariable ["cti_town_neighbors", [Vyshnoye, Pusta, Nadezhdino, Staroye, Chernogorsk]];
		Pusta setVariable ["cti_town_neighbors", [Mogilevka, Elektrozavodsk, Prigorodki, Staroye]];
		Staroye setVariable ["cti_town_neighbors", [Shakhovka, Guglovo, Elektrozavodsk, Msta, Mogilevka, Pusta, Dolina]];
		Msta setVariable ["cti_town_neighbors", [Staroye, Kamyshovo, Solnichniy, Dolina, Tulga]];
		Dolina setVariable ["cti_town_neighbors", [Staroye, Solnichniy, Shakhovka, Polana, Msta, Orlovets]];
		Orlovets setVariable ["cti_town_neighbors", [Nizhnoye, Polana, Dolina, Solnichniy]];
		Polana setVariable ["cti_town_neighbors", [Orlovets, Dolina, Shakhovka, Gorka]];
		Gorka setVariable ["cti_town_neighbors", [Dubrovka, Polana, Guglovo, Altar]];
		Dubrovka setVariable ["cti_town_neighbors", [Gorka, Krasnostav, Berezino, Khelm, Altar, Gvozdno]];
		Shakhovka setVariable ["cti_town_neighbors", [Staroye, Polana, Dolina, Guglovo]];
		Guglovo setVariable ["cti_town_neighbors", [Staroye, NovySobor, Shakhovka, Vyshnoye, Gorka]];
		Vyshnoye setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Mogilevka, Nadezhdino, Pogorevka]];
		StarySobor setVariable ["cti_town_neighbors", [Vyshnoye, Kabanino, Pogorevka, NovySobor]];
		Pogorevka setVariable ["cti_town_neighbors", [Zelenogorsk, StarySobor, Vyshnoye, Pustoshka, Kozlovka, Vybor, Kabanino]];
		Kabanino setVariable ["cti_town_neighbors", [Vybor, Grishino, StarySobor, Pogorevka, Airfield]];
		Vybor setVariable ["cti_town_neighbors", [Kabanino, Lopatino, Pustoshka, Pogorevka, Airfield]];
		Pustoshka setVariable ["cti_town_neighbors", [Vybor, Myshkino, Lopatino, Pogorevka]];
		Hill366 setVariable ["cti_town_neighbors", [Gvozdno, Krasnostav, DevilsCastle, Petrovka]];
		Airfield setVariable ["cti_town_neighbors", [Vybor, Lopatino, Kabanino, Petrovka, Grishino]];
		Tulga setVariable ["cti_town_neighbors", [Solnichniy, Kamyshovo, Msta]];
		Altar setVariable ["cti_town_neighbors", [NovySobor, Gorka, Gvozdno, Grishino]];
		DevilsCastle setVariable ["cti_town_neighbors", [Grishino, Gvozdno, Petrovka, Hill366]];
		NovySobor setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Altar]];
		WindFarm setVariable ["cti_town_neighbors", [Elektrozavodsk, USSWasp, FuelDepot]];
		FuelDepot setVariable ["cti_town_neighbors", [Chernogorsk, WindFarm, Elektrozavodsk]];
		USSWasp setVariable ["cti_town_neighbors", [Solnichniy, Nizhnoye, WindFarm, Olsha]];
		Bor setVariable ["cti_town_neighbors", [Zelenogorsk, Kozlovka, Pavlovo, Komarovo]];
	};
	case "chernarus_2035": {
		Kamenka setVariable ["cti_town_neighbors", [Pavlovo, Komarovo, NorvorskNuclearPlant]];
		Skalka setVariable ["cti_town_neighbors", [PetrovkaNuclearPlant, Airfield, Lopatino]];
		Komarovo setVariable ["cti_town_neighbors", [Pavlovo, Balota, Kamenka]];
		Balota setVariable ["cti_town_neighbors", [Kozlovka, Komarovo, Chernogorsk]];
		Chernogorsk setVariable ["cti_town_neighbors", [Balota, Nadezhdino, Prigorodki, Kozlovka, Mogilevka, FuelDepot]];
		Prigorodki setVariable ["cti_town_neighbors", [Chernogorsk, Elektrozavodsk, Pusta]];
		Elektrozavodsk setVariable ["cti_town_neighbors", [Prigorodki, Pusta, Kamyshovo, Staroye, WindFarm, FuelDepot]];
		Kamyshovo setVariable ["cti_town_neighbors", [Elektrozavodsk, Msta, Tulga]];
		Solnichniy setVariable ["cti_town_neighbors", [Msta, Nizhnoye, Dolina, Orlovets, Tulga, USSWasp]];
		Nizhnoye setVariable ["cti_town_neighbors", [Solnichniy, Berezino, USSWasp, Orlovets]];
		Berezino setVariable ["cti_town_neighbors", [Nizhnoye, Khelm, Orlovets, Dubrovka]];
		Khelm setVariable ["cti_town_neighbors", [Berezino, Krasnostav, Olsha]];
		Krasnostav setVariable ["cti_town_neighbors", [Olsha, Gvozdno, Dubrovka, Khelm, Belyov]];
		Olsha setVariable ["cti_town_neighbors", [Krasnostav, Khelm, Guba]];
		Gvozdno setVariable ["cti_town_neighbors", [Krasnostav, Grishino, Dubrovka, Hill366, Altar, DevilsCastle, Belyov]];
		Grishino setVariable ["cti_town_neighbors", [Gvozdno, PetrovkaNuclearPlant, Kabanino, AirField, Altar, DevilsCastle]];
		PetrovkaNuclearPlant setVariable ["cti_town_neighbors", [Grishino, Airfield, DevilsCastle, Hill366, Skalka]];
		Lopatino setVariable ["cti_town_neighbors", [Vybor, Pustoshka, Airfield, Skalka]];
		Myshkino setVariable ["cti_town_neighbors", [Zelenogorsk, Pustoshka]];
		Zelenogorsk setVariable ["cti_town_neighbors", [Myshkino, Pogorevka, Kozlovka, Pavlovo]];
		Pavlovo setVariable ["cti_town_neighbors", [Kamenka, Komarovo, Zelenogorsk]];
		Kozlovka setVariable ["cti_town_neighbors", [Zelenogorsk, Nadezhdino, Chernogorsk, Balota, Pogorevka]];
		Nadezhdino setVariable ["cti_town_neighbors", [Kozlovka, Chernogorsk, Mogilevka, Vyshnoye]];
		Mogilevka setVariable ["cti_town_neighbors", [Vyshnoye, Pusta, Nadezhdino, Staroye, Chernogorsk]];
		Pusta setVariable ["cti_town_neighbors", [Mogilevka, Elektrozavodsk, Prigorodki, Staroye]];
		Staroye setVariable ["cti_town_neighbors", [Shakhovka, Guglovo, Elektrozavodsk, Msta, Mogilevka, Pusta, Dolina]];
		Msta setVariable ["cti_town_neighbors", [Staroye, Kamyshovo, Solnichniy, Dolina, Tulga]];
		Dolina setVariable ["cti_town_neighbors", [Staroye, Solnichniy, Shakhovka, Polana, Msta, Orlovets]];
		Orlovets setVariable ["cti_town_neighbors", [Nizhnoye, Polana, Dolina, Solnichniy]];
		Polana setVariable ["cti_town_neighbors", [Orlovets, Dolina, Shakhovka, Gorka]];
		Gorka setVariable ["cti_town_neighbors", [Dubrovka, Polana, Guglovo, Altar]];
		Dubrovka setVariable ["cti_town_neighbors", [Gorka, Krasnostav, Berezino, Khelm, Altar, Gvozdno]];
		Shakhovka setVariable ["cti_town_neighbors", [Staroye, Polana, Dolina, Guglovo]];
		Guglovo setVariable ["cti_town_neighbors", [Staroye, NovySobor, Shakhovka, Vyshnoye, Gorka]];
		Vyshnoye setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Mogilevka, Nadezhdino, Pogorevka]];
		StarySobor setVariable ["cti_town_neighbors", [Vyshnoye, Kabanino, Pogorevka, NovySobor]];
		Pogorevka setVariable ["cti_town_neighbors", [Zelenogorsk, StarySobor, Vyshnoye, Pustoshka, Kozlovka, Vybor, Kabanino]];
		Kabanino setVariable ["cti_town_neighbors", [Vybor, Grishino, StarySobor, Pogorevka, Airfield]];
		Vybor setVariable ["cti_town_neighbors", [Kabanino, Lopatino, Pustoshka, Pogorevka, Airfield]];
		Pustoshka setVariable ["cti_town_neighbors", [Vybor, Myshkino, Lopatino, Pogorevka]];
		Hill366 setVariable ["cti_town_neighbors", [Gvozdno, DevilsCastle, PetrovkaNuclearPlant, Belyov]];
		Airfield setVariable ["cti_town_neighbors", [Vybor, Lopatino, Kabanino, PetrovkaNuclearPlant, Grishino, Skalka]];
		Tulga setVariable ["cti_town_neighbors", [Solnichniy, Kamyshovo, Msta]];
		Altar setVariable ["cti_town_neighbors", [NovySobor, Gorka, Gvozdno, Grishino]];
		DevilsCastle setVariable ["cti_town_neighbors", [Grishino, Gvozdno, PetrovkaNuclearPlant, Hill366]];
		NovySobor setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Altar]];
		WindFarm setVariable ["cti_town_neighbors", [Elektrozavodsk, USSWasp, Utes, VehrynIsland, FuelDepot]];
		FuelDepot setVariable ["cti_town_neighbors", [Chernogorsk, WindFarm, Elektrozavodsk, NorvorskNuclearPlant, VulskIsland, VehrynIsland]];
		USSWasp setVariable ["cti_town_neighbors", [Solnichniy, Nizhnoye, WindFarm, Guba]];
		NorvorskNuclearPlant setVariable ["cti_town_neighbors", [Kamenka, FuelDepot, VulskIsland]];
		VulskIsland setVariable ["cti_town_neighbors", [NorvorskNuclearPlant, FuelDepot, Utes, VehrynIsland]];
		Utes setVariable ["cti_town_neighbors", [VulskIsland, WindFarm, VehrynIsland]];
		VehrynIsland setVariable ["cti_town_neighbors", [Utes, VulskIsland, FuelDepot, WindFarm]];
		Guba setVariable ["cti_town_neighbors", [Olsha, Belyov, USSWasp, RunwayInProgress]];
		Belyov setVariable ["cti_town_neighbors", [Guba, Krasnostav, Gvozdno, Hill366]];
		RunwayInProgress setVariable ["cti_town_neighbors", [Guba]];
	};
	case "chernarus_winter": {
		Kamenka setVariable ["cti_town_neighbors", [Pavlovo, Komarovo]];
		Komarovo setVariable ["cti_town_neighbors", [Bor, Balota, Kamenka]];
		Balota setVariable ["cti_town_neighbors", [Kozlovka, Komarovo, Chernogorsk]];
		Chernogorsk setVariable ["cti_town_neighbors", [Balota, Nadezhdino, Prigorodki, Kozlovka, Mogilevka, FuelDepot]];
		Prigorodki setVariable ["cti_town_neighbors", [Chernogorsk, Elektrozavodsk, Pusta]];
		Elektrozavodsk setVariable ["cti_town_neighbors", [Prigorodki, Pusta, Kamyshovo, Staroye, WindFarm, FuelDepot]];
		Kamyshovo setVariable ["cti_town_neighbors", [Elektrozavodsk, Msta, Tulga]];
		Solnichniy setVariable ["cti_town_neighbors", [Msta, Nizhnoye, Dolina, Orlovets, Tulga, USSWasp]];
		Nizhnoye setVariable ["cti_town_neighbors", [Solnichniy, Berezino, USSWasp, Orlovets]];
		Berezino setVariable ["cti_town_neighbors", [Nizhnoye, Khelm, Orlovets, Dubrovka]];
		Khelm setVariable ["cti_town_neighbors", [Berezino, Krasnostav, Olsha, Dubrovka]];
		Krasnostav setVariable ["cti_town_neighbors", [Olsha, Gvozdno, Dubrovka, Khelm, Hill366]];
		Olsha setVariable ["cti_town_neighbors", [Krasnostav, Khelm,USSWasp]];
		Gvozdno setVariable ["cti_town_neighbors", [Krasnostav, Grishino, Dubrovka, Hill366, Altar, DevilsCastle]];
		Grishino setVariable ["cti_town_neighbors", [Gvozdno, Petrovka, Kabanino, AirField, Altar, DevilsCastle]];
		Petrovka setVariable ["cti_town_neighbors", [Grishino, Lopatino, Airfield, DevilsCastle, Hill366]];
		Lopatino setVariable ["cti_town_neighbors", [Petrovka, Vybor, Pustoshka, Airfield]];
		Myshkino setVariable ["cti_town_neighbors", [Zelenogorsk, Pustoshka]];
		Zelenogorsk setVariable ["cti_town_neighbors", [Myshkino, Pogorevka, Kozlovka, Pavlovo, Bor]];
		Pavlovo setVariable ["cti_town_neighbors", [Kamenka, Zelenogorsk, Bor]];
		Kozlovka setVariable ["cti_town_neighbors", [Zelenogorsk, Nadezhdino, Chernogorsk, Balota, Pogorevka, Bor]];
		Nadezhdino setVariable ["cti_town_neighbors", [Kozlovka, Chernogorsk, Mogilevka, Vyshnoye]];
		Mogilevka setVariable ["cti_town_neighbors", [Vyshnoye, Pusta, Nadezhdino, Staroye, Chernogorsk]];
		Pusta setVariable ["cti_town_neighbors", [Mogilevka, Elektrozavodsk, Prigorodki, Staroye]];
		Staroye setVariable ["cti_town_neighbors", [Shakhovka, Guglovo, Elektrozavodsk, Msta, Mogilevka, Pusta, Dolina]];
		Msta setVariable ["cti_town_neighbors", [Staroye, Kamyshovo, Solnichniy, Dolina, Tulga]];
		Dolina setVariable ["cti_town_neighbors", [Staroye, Solnichniy, Shakhovka, Polana, Msta, Orlovets]];
		Orlovets setVariable ["cti_town_neighbors", [Nizhnoye, Polana, Dolina, Solnichniy]];
		Polana setVariable ["cti_town_neighbors", [Orlovets, Dolina, Shakhovka, Gorka]];
		Gorka setVariable ["cti_town_neighbors", [Dubrovka, Polana, Guglovo, Altar]];
		Dubrovka setVariable ["cti_town_neighbors", [Gorka, Krasnostav, Berezino, Khelm, Altar, Gvozdno]];
		Shakhovka setVariable ["cti_town_neighbors", [Staroye, Polana, Dolina, Guglovo]];
		Guglovo setVariable ["cti_town_neighbors", [Staroye, NovySobor, Shakhovka, Vyshnoye, Gorka]];
		Vyshnoye setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Mogilevka, Nadezhdino, Pogorevka]];
		StarySobor setVariable ["cti_town_neighbors", [Vyshnoye, Kabanino, Pogorevka, NovySobor]];
		Pogorevka setVariable ["cti_town_neighbors", [Zelenogorsk, StarySobor, Vyshnoye, Pustoshka, Kozlovka, Vybor, Kabanino]];
		Kabanino setVariable ["cti_town_neighbors", [Vybor, Grishino, StarySobor, Pogorevka, Airfield]];
		Vybor setVariable ["cti_town_neighbors", [Kabanino, Lopatino, Pustoshka, Pogorevka, Airfield]];
		Pustoshka setVariable ["cti_town_neighbors", [Vybor, Myshkino, Lopatino, Pogorevka]];
		Hill366 setVariable ["cti_town_neighbors", [Gvozdno, Krasnostav, DevilsCastle, Petrovka]];
		Airfield setVariable ["cti_town_neighbors", [Vybor, Lopatino, Kabanino, Petrovka, Grishino]];
		Tulga setVariable ["cti_town_neighbors", [Solnichniy, Kamyshovo, Msta]];
		Altar setVariable ["cti_town_neighbors", [NovySobor, Gorka, Gvozdno, Grishino]];
		DevilsCastle setVariable ["cti_town_neighbors", [Grishino, Gvozdno, Petrovka, Hill366]];
		NovySobor setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Altar]];
		WindFarm setVariable ["cti_town_neighbors", [Elektrozavodsk, USSWasp, FuelDepot]];
		FuelDepot setVariable ["cti_town_neighbors", [Chernogorsk, WindFarm, Elektrozavodsk]];
		USSWasp setVariable ["cti_town_neighbors", [Solnichniy, Nizhnoye, WindFarm, Olsha]];
		Bor setVariable ["cti_town_neighbors", [Zelenogorsk, Kozlovka, Pavlovo, Komarovo]];
	};
	case "sara_dbe1": {
		IslaDelVida setVariable ["cti_town_neighbors",[Hunapu,WorkCamp,FuelDepot]];
		Hunapu setVariable ["cti_town_neighbors",[IslaDelVida,WorkCamp,Pacamac]];
		WorkCamp setVariable ["cti_town_neighbors",[IslaDelVida,Hunapu,Malaredo]];
		Pacamac setVariable ["cti_town_neighbors",[Hunapu,Malaredo,Tlaloc,OilRig]];
		Malaredo setVariable ["cti_town_neighbors",[WorkCamp,Pacamac,RockQuarry,Epomia]];
		RockQuarry setVariable ["cti_town_neighbors",[Malaredo,RocaDelDror]];
		RocaDelDror setVariable ["cti_town_neighbors",[Epomia,RockQuarry,Antigua]];
		Epomia setVariable ["cti_town_neighbors",[Malaredo,RocaDelDror,Carmen]];
		Carmen setVariable ["cti_town_neighbors",[Epomia,Tlaloc,Bagango]];
		Tlaloc setVariable ["cti_town_neighbors",[Pacamac,OilRig,Carmen,Mercalillo]];
		Benoma setVariable ["cti_town_neighbors",[Bagango,Masbee]];
		Bagango setVariable ["cti_town_neighbors",[Mercalillo,Obregan,Benoma,Carmen]];
		Mercalillo setVariable ["cti_town_neighbors",[Tlaloc,Bagango,Obregan]];
		Masbee setVariable ["cti_town_neighbors",[Antigua,Benoma,Pita,TresValles]];
		Pita setVariable ["cti_town_neighbors",[Masbee,TresValles]];
		TresValles setVariable ["cti_town_neighbors",[Masbee,Pita,Everon]];
		Everon setVariable ["cti_town_neighbors",[TresValles,Obregan,Modesta,WindFarm]];
		Obregan setVariable ["cti_town_neighbors",[Mercalillo,Bagango,Everon,Modesta]];
		Modesta setVariable ["cti_town_neighbors",[Everon,Corazol,Obregan]];
		Corazol setVariable ["cti_town_neighbors",[Modesta,Ortego,Paraiso]];
		Rashidah setVariable ["cti_town_neighbors",[Paraiso,Chantico,OilRig]];
		Paraiso setVariable ["cti_town_neighbors",[Corazol,Somato,Rashidah]];
		Somato setVariable ["cti_town_neighbors",[Paraiso,Chantico,Cayo]];
		Chantico setVariable ["cti_town_neighbors",[Rashidah,Somato,Estrella]];
		Estrella setVariable ["cti_town_neighbors",[Chantico,FuelDepot,Arcadia]];
		Arcadia setVariable ["cti_town_neighbors",[Estrella,Cayo,Rahmadi]];
		Cayo setVariable ["cti_town_neighbors",[Somato,Arcadia,Iguana,Dolores]];
		Iguana setVariable ["cti_town_neighbors",[Cayo,Dolores,WindFarm,USSWasp]];
		Dolores setVariable ["cti_town_neighbors",[Cayo,Iguana,Ortego,WindFarm]];
		Ortego setVariable ["cti_town_neighbors",[Corazol,Dolores]];
		Antigua setVariable ["cti_town_neighbors",[RocaDelDror,Masbee]];
		Rahmadi setVariable ["cti_town_neighbors",[Arcadia,FuelDepot,USSWasp]];
		FuelDepot setVariable ["cti_town_neighbors",[IslaDelVida,Estrella,Rahmadi,OilRig]];
		OilRig setVariable ["cti_town_neighbors",[Tlaloc,Pacamac,Rashidah,FuelDepot]];
		WindFarm setVariable ["cti_town_neighbors",[Everon,Iguana,Dolores,USSWasp]];
		USSWasp setVariable ["cti_town_neighbors", [WindFarm,Rahmadi,Iguana]];
	};
	case "takistan": {
		Nur setVariable ["cti_town_neighbors", [Nagara]];
		Nagara setVariable ["cti_town_neighbors", [Nur,Shamali,Gospandi,Rasman]];
		Shamali setVariable ["cti_town_neighbors", [Nagara,Rasman]];
		Rasman setVariable ["cti_town_neighbors", [Nagara,Bastam,Shamali,Zavarak]];
		Gospandi setVariable ["cti_town_neighbors", [Nagara,Mulladost,Bastam]];
		Mulladost setVariable ["cti_town_neighbors", [Gospandi,Khushab]];
		Khushab setVariable ["cti_town_neighbors", [Mulladost, Jilavur]];
		Jilavur setVariable ["cti_town_neighbors", [Khushab,Sakhe,FeruzAbad,Shukurkalay]];
		Shukurkalay setVariable ["cti_town_neighbors", [Jilavur, Chaman]];
		Chaman setVariable ["cti_town_neighbors", [Shukurkalay]];
		Sakhe setVariable ["cti_town_neighbors", [Jilavur,ChakChak,FeruzAbad,Kakaru]];
		ChakChak setVariable ["cti_town_neighbors", [Sakhe,Landay,Huzrutimam,Kakaru]];
		Landay setVariable ["cti_town_neighbors", [ChakChak]];
		Huzrutimam setVariable ["cti_town_neighbors", [ChakChak,Sultansafe]];
		Sultansafe setVariable ["cti_town_neighbors", [Huzrutimam,LoyManara]];
		LoyManara setVariable ["cti_town_neighbors", [Sultansafe,Jaza,Chardarakht,Timurkalay]];
		Jaza setVariable ["cti_town_neighbors", [LoyManara,Chardarakht]];
		Chardarakht setVariable ["cti_town_neighbors", [Jaza,LoyManara,HazarBagh]];
		HazarBagh setVariable ["cti_town_neighbors", [Chardarakht]];
		Timurkalay setVariable ["cti_town_neighbors", [LoyManara,Anar,Garmarud]];
		Anar setVariable ["cti_town_neighbors", [Timurkalay,FeruzAbad,Kakaru,Falar]];
		FeruzAbad setVariable ["cti_town_neighbors", [Jilavur,Anar,Sakhe,Kakaru,Falar]];
		Kakaru setVariable ["cti_town_neighbors", [FeruzAbad,ChakChak,Anar,Sakhe]];
		Falar setVariable ["cti_town_neighbors", [FeruzAbad,Anar,Bastam]];
		Bastam setVariable ["cti_town_neighbors", [Rasman,Gospandi,Falar,Imarat]];
		Imarat setVariable ["cti_town_neighbors", [Bastam,Zavarak,Garmarud]];
		Garmarud setVariable ["cti_town_neighbors", [Imarat,Timurkalay,Garmsar]];
		Garmsar setVariable ["cti_town_neighbors", [Garmarud]];
		Zavarak setVariable ["cti_town_neighbors", [Imarat,Ravanay,Karachinar,Rasman]];
		Ravanay setVariable ["cti_town_neighbors", [Zavarak,Karachinar]];
		Karachinar setVariable ["cti_town_neighbors", [Zavarak,Ravanay]];
	};
	case "beketov": {
		Sentsy setVariable ["cti_town_neighbors",[OutpostJordan,KrasyneSeltsy]];
		KrasyneSeltsy setVariable ["cti_town_neighbors",[Shalaevo,Sentsy,Polshishkino]];
		Polivanovo setVariable ["cti_town_neighbors",[Shalaevo,Zhukovo,Polshishkino]];
		Polshishkino setVariable ["cti_town_neighbors",[Shalaevo,KrasyneSeltsy,Zhukovo,Polshishkino,Mikhalevo]];
		Zhukovo setVariable ["cti_town_neighbors",[Polivanovo,Polshishkino,Kuzhadon]];
		Kuzhadon setVariable ["cti_town_neighbors",[Zhukovo,Armanikha,Shpagino]];
		Shpagino setVariable ["cti_town_neighbors",[Kuzhadon,NorthWestBeketov]];
		Armanikha setVariable ["cti_town_neighbors",[Kuzhadon,NorthWestBeketov]];
		NorthWestBeketov setVariable ["cti_town_neighbors",[SouthBeketov,EastBeketov,Armanikha,Shpagino]];
		SouthBeketov setVariable ["cti_town_neighbors",[NorthWestBeketov,EastBeketov]];
		EastBeketov setVariable ["cti_town_neighbors",[NorthWestBeketov,SouthBeketov,Gavrikolvka]];
		Gavrikolvka setVariable ["cti_town_neighbors",[EastBeketov,Sevastianovo,Dorogino]];
		Sevastianovo setVariable ["cti_town_neighbors",[Gavrikolvka,Siukha,Mikhalevo]];
		Mikhalevo setVariable ["cti_town_neighbors",[Polshishkino,Siukha,Sevastianovo]];
		Siukha setVariable ["cti_town_neighbors",[Mikhalevo,LakeEusovo,Sevastianovo,Vorontsovo]];
		Dorogino setVariable ["cti_town_neighbors",[Gavrikolvka,LakeEusovo,Imeni,Naleskino]];
		Imeni setVariable ["cti_town_neighbors",[Dorogino,LakeEusovo,Naleskino]];
		Naleskino setVariable ["cti_town_neighbors",[Dorogino,Imeni,Vizovino]];
		Vizovino setVariable ["cti_town_neighbors",[Dorogino,Vizovino]];	
		LakeEusovo setVariable ["cti_town_neighbors",[Dorogino,Imeni,Siukha,Studenets]];
		Vorontsovo setVariable ["cti_town_neighbors",[Studenets,Siukha,Arshavino]];
		Studenets  setVariable ["cti_town_neighbors",[Vorontsovo,LakeEusovo,Arshavino]];
		Arshavino setVariable ["cti_town_neighbors",[Vorontsovo,Studenets,Dubionki]];
		Dubionki setVariable ["cti_town_neighbors",[Arshavino,OutpostJordan]];
		OutpostJordan setVariable ["cti_town_neighbors",[Dubionki,Sentsy]];
		Shalaevo setVariable ["cti_town_neighbors",[Polivanovo,Polshishkino,KrasyneSeltsy]];
	};
	case "napf": {
		Bernerplatte setVariable ["cti_town_neighbors",[Airbase,Feldmoos]];
		Feldmoos setVariable ["cti_town_neighbors",[Bernerplatte,Worb]];
		Worb setVariable ["cti_town_neighbors",[Feldmoos,Airbase,Signau,Ittingen]];
		Hindelbank setVariable ["cti_town_neighbors",[FuelDepot,Ittingen,Huttwil,Unterdorf]];
		FuelDepot setVariable ["cti_town_neighbors",[Hindelbank,Bubendorf,OilRig]];
		OilRig setVariable ["cti_town_neighbors",[FuelDepot,Seltisberg,Hafen]];
		Bubendorf setVariable ["cti_town_neighbors",[Huttwil,FuelDepot,Seltisberg]];
		Huttwil setVariable ["cti_town_neighbors",[Unterdorf,Muttenz,Bubendorf,NeueWelt,Hindelbank]];
		Seltisberg setVariable ["cti_town_neighbors",[Bubendorf,NeueWelt,OilRig,Trueb,Lenzburg]];
		NeueWelt setVariable ["cti_town_neighbors",[Huttwil,Seltisberg,Trueb]];
		Muttenz setVariable ["cti_town_neighbors",[Signau,Huttwil,Unterdorf]];
		Signau setVariable ["cti_town_neighbors",[Eggwil,Worb,Muttenz,Chatzbach]];
		Chatzbach setVariable ["cti_town_neighbors",[Ramsebode,Bruderholz,Signau]];
		Eggwil setVariable ["cti_town_neighbors",[Airbase,Schangen,Signau]];
		Airbase setVariable ["cti_town_neighbors",[Bernerplatte,Worb,Eggwil,Schangen,CoastalFARP]];
		Hungerschwand setVariable ["cti_town_neighbors",[Schangen,Goldwil,Waldegg]];
		Schangen setVariable ["cti_town_neighbors",[Airbase,Hungerschwand,Schrattendamm,Eggwil,Ramsebode]];
		Schrattendamm setVariable ["cti_town_neighbors",[Schangen,Sorenberg,Hill474]];
		Goldwil setVariable ["cti_town_neighbors",[Hungerschwand,Hill474,WindFarm]];
		WindFarm setVariable ["cti_town_neighbors",[Goldwil,Brienz,SouthAirstrip]];
		Brienz setVariable ["cti_town_neighbors",[Hill474,WindFarm,Froburg,Sorenberg]];
		Froburg setVariable ["cti_town_neighbors",[Brienz,SouthAirstrip,Giswil]];
		SouthAirstrip setVariable ["cti_town_neighbors",[Froburg,WindFarm]];
		Giswil setVariable ["cti_town_neighbors",[Froburg,Hill248,Rorenpass]];
		Village setVariable ["cti_town_neighbors",[Hill248,Alpnach]];
		Sorenberg setVariable ["cti_town_neighbors",[Brienz,Farnen,Schrattendamm,Hill474,Rorenpass]];
		Farnen setVariable ["cti_town_neighbors",[Sorenberg,Liestal,Hill314]];
		Ramsebode setVariable ["cti_town_neighbors",[Schangen,Liestal,Chatzbach,Bruderholz]];
		Bruderholz setVariable ["cti_town_neighbors",[Ramsebode,Chatzbach,NapfCastle]];
		Eichmatt setVariable ["cti_town_neighbors",[Trueb,NapfCastle]];
		Lenzburg setVariable ["cti_town_neighbors",[Seltisberg,Trueb,Hafen,Olten,Hafen]];
		Hafen setVariable ["cti_town_neighbors",[OilRig,Lenzburg,Olten]];
		Olten setVariable ["cti_town_neighbors",[Lenzburg,Hafen,Lausen,Hirsegg,Nordstern]];
		Hirsegg setVariable ["cti_town_neighbors",[Trueb,Olten,Lausen,NapfCastle]];
		Lausen setVariable ["cti_town_neighbors",[Olten,Hirsegg,Luzern,Mayak]];
		NapfCastle setVariable ["cti_town_neighbors",[Hirsegg,Eichmatt,Bruderholz,Romoos]];
		Liestal setVariable ["cti_town_neighbors",[Sachseln,Ramsebode,Farnen,Romoos,Wolhusen]];
		Schimbrig setVariable ["cti_town_neighbors",[Alpnach,Sachseln,Hill314]];
		Alpnach setVariable ["cti_town_neighbors",[Village,Schimbrig,Pfeffikon]];
		Sachseln setVariable ["cti_town_neighbors",[Schimbrig,Liestal,Wolhusen]];
		Romoos setVariable ["cti_town_neighbors",[NapfCastle,Liestal,Wolhusen]];
		Wolhusen setVariable ["cti_town_neighbors",[Romoos,Luzern,Liestal,Sachseln,Horw]];
		Luzern setVariable ["cti_town_neighbors",[Lausen,Wolhusen,InternationalAir,Horw]];
		Horw setVariable ["cti_town_neighbors",[Luzern,InternationalAir,Pfeffikon,Wolhusen]];
		InternationalAir setVariable ["cti_town_neighbors",[Luzern,Horw,Suhrenfeld,Mayak]];
		Suhrenfeld setVariable ["cti_town_neighbors",[Pfeffikon,InternationalAir]];
		Pfeffikon setVariable ["cti_town_neighbors",[Horw,Suhrenfeld,Alpnach]];
		Trueb setVariable ["cti_town_neighbors",[Hirsegg,Seltisberg,NeueWelt,Lenzburg,Eichmatt]];
		Unterdorf setVariable ["cti_town_neighbors",[Muttenz,Hasle,Hindelbank,Huttwil]];
		Ittingen setVariable ["cti_town_neighbors",[Worb,Hasle,Hindelbank]];
		Hasle setVariable ["cti_town_neighbors",[Ittingen,Unterdorf]];
		Waldegg setVariable ["cti_town_neighbors",[Hungerschwand,CoastalFARP]];
		Nordstern setVariable ["cti_town_neighbors",[Olten]];
		Mayak setVariable ["cti_town_neighbors",[Lausen,InternationalAir]];
		Rorenpass setVariable ["cti_town_neighbors",[Sorenberg,Giswil,Hill314]];
		Hill314 setVariable ["cti_town_neighbors",[Farnen,Rorenpass,Schimbrig]];
		Hill248 setVariable ["cti_town_neighbors",[Village,Giswil]];
		Hill474 setVariable ["cti_town_neighbors",[Goldwil,Brienz,Schrattendamm,Sorenberg]];
		CoastalFARP setVariable ["cti_town_neighbors",[Waldegg,Airbase]];

	};
	case "napfwinter": {
		Bernerplatte setVariable ["cti_town_neighbors",[Airbase,Feldmoos]];
		Feldmoos setVariable ["cti_town_neighbors",[Bernerplatte,Worb]];
		Worb setVariable ["cti_town_neighbors",[Feldmoos,Airbase,Signau,Ittingen]];
		Hindelbank setVariable ["cti_town_neighbors",[FuelDepot,Ittingen,Huttwil,Unterdorf]];
		FuelDepot setVariable ["cti_town_neighbors",[Hindelbank,Bubendorf,OilRig]];
		OilRig setVariable ["cti_town_neighbors",[FuelDepot,Seltisberg,Hafen]];
		Bubendorf setVariable ["cti_town_neighbors",[Huttwil,FuelDepot,Seltisberg]];
		Huttwil setVariable ["cti_town_neighbors",[Unterdorf,Muttenz,Bubendorf,NeueWelt,Hindelbank]];
		Seltisberg setVariable ["cti_town_neighbors",[Bubendorf,NeueWelt,OilRig,Trueb,Lenzburg]];
		NeueWelt setVariable ["cti_town_neighbors",[Huttwil,Seltisberg,Trueb]];
		Muttenz setVariable ["cti_town_neighbors",[Signau,Huttwil,Unterdorf]];
		Signau setVariable ["cti_town_neighbors",[Eggwil,Worb,Muttenz,Chatzbach]];
		Chatzbach setVariable ["cti_town_neighbors",[Ramsebode,Bruderholz,Signau]];
		Eggwil setVariable ["cti_town_neighbors",[Airbase,Schangen,Signau]];
		Airbase setVariable ["cti_town_neighbors",[Bernerplatte,Worb,Eggwil,Schangen,CoastalFARP]];
		Hungerschwand setVariable ["cti_town_neighbors",[Schangen,Goldwil,Waldegg]];
		Schangen setVariable ["cti_town_neighbors",[Airbase,Hungerschwand,Schrattendamm,Eggwil,Ramsebode]];
		Schrattendamm setVariable ["cti_town_neighbors",[Schangen,Sorenberg,Hill474]];
		Goldwil setVariable ["cti_town_neighbors",[Hungerschwand,Hill474,WindFarm]];
		WindFarm setVariable ["cti_town_neighbors",[Goldwil,Brienz,SouthAirstrip]];
		Brienz setVariable ["cti_town_neighbors",[Hill474,WindFarm,Froburg,Sorenberg]];
		Froburg setVariable ["cti_town_neighbors",[Brienz,SouthAirstrip,Giswil]];
		SouthAirstrip setVariable ["cti_town_neighbors",[Froburg,WindFarm]];
		Giswil setVariable ["cti_town_neighbors",[Froburg,Hill248,Rorenpass]];
		Village setVariable ["cti_town_neighbors",[Hill248,Alpnach]];
		Sorenberg setVariable ["cti_town_neighbors",[Brienz,Farnen,Schrattendamm,Hill474,Rorenpass]];
		Farnen setVariable ["cti_town_neighbors",[Sorenberg,Liestal,Hill314]];
		Ramsebode setVariable ["cti_town_neighbors",[Schangen,Liestal,Chatzbach,Bruderholz]];
		Bruderholz setVariable ["cti_town_neighbors",[Ramsebode,Chatzbach,NapfCastle]];
		Eichmatt setVariable ["cti_town_neighbors",[Trueb,NapfCastle]];
		Lenzburg setVariable ["cti_town_neighbors",[Seltisberg,Trueb,Hafen,Olten,Hafen]];
		Hafen setVariable ["cti_town_neighbors",[OilRig,Lenzburg,Olten]];
		Olten setVariable ["cti_town_neighbors",[Lenzburg,Hafen,Lausen,Hirsegg,Nordstern]];
		Hirsegg setVariable ["cti_town_neighbors",[Trueb,Olten,Lausen,NapfCastle]];
		Lausen setVariable ["cti_town_neighbors",[Olten,Hirsegg,Luzern,Mayak]];
		NapfCastle setVariable ["cti_town_neighbors",[Hirsegg,Eichmatt,Bruderholz,Romoos]];
		Liestal setVariable ["cti_town_neighbors",[Sachseln,Ramsebode,Farnen,Romoos,Wolhusen]];
		Schimbrig setVariable ["cti_town_neighbors",[Alpnach,Sachseln,Hill314]];
		Alpnach setVariable ["cti_town_neighbors",[Village,Schimbrig,Pfeffikon]];
		Sachseln setVariable ["cti_town_neighbors",[Schimbrig,Liestal,Wolhusen]];
		Romoos setVariable ["cti_town_neighbors",[NapfCastle,Liestal,Wolhusen]];
		Wolhusen setVariable ["cti_town_neighbors",[Romoos,Luzern,Liestal,Sachseln,Horw]];
		Luzern setVariable ["cti_town_neighbors",[Lausen,Wolhusen,InternationalAir,Horw]];
		Horw setVariable ["cti_town_neighbors",[Luzern,InternationalAir,Pfeffikon,Wolhusen]];
		InternationalAir setVariable ["cti_town_neighbors",[Luzern,Horw,Suhrenfeld,Mayak]];
		Suhrenfeld setVariable ["cti_town_neighbors",[Pfeffikon,InternationalAir]];
		Pfeffikon setVariable ["cti_town_neighbors",[Horw,Suhrenfeld,Alpnach]];
		Trueb setVariable ["cti_town_neighbors",[Hirsegg,Seltisberg,NeueWelt,Lenzburg,Eichmatt]];
		Unterdorf setVariable ["cti_town_neighbors",[Muttenz,Hasle,Hindelbank,Huttwil]];
		Ittingen setVariable ["cti_town_neighbors",[Worb,Hasle,Hindelbank]];
		Hasle setVariable ["cti_town_neighbors",[Ittingen,Unterdorf]];
		Waldegg setVariable ["cti_town_neighbors",[Hungerschwand,CoastalFARP]];
		Nordstern setVariable ["cti_town_neighbors",[Olten]];
		Mayak setVariable ["cti_town_neighbors",[Lausen,InternationalAir]];
		Rorenpass setVariable ["cti_town_neighbors",[Sorenberg,Giswil,Hill314]];
		Hill314 setVariable ["cti_town_neighbors",[Farnen,Rorenpass,Schimbrig]];
		Hill248 setVariable ["cti_town_neighbors",[Village,Giswil]];
		Hill474 setVariable ["cti_town_neighbors",[Goldwil,Brienz,Schrattendamm,Sorenberg]];
		CoastalFARP setVariable ["cti_town_neighbors",[Waldegg,Airbase]];
		
	};
	case "australia": {
		WindFarmAlpha setVariable ["cti_town_neighbors",[RadarOutpost,OilRigFoxtrot,Cairns]];
		WindFarmBravo setVariable ["cti_town_neighbors",[OilRigIndia,PortLincoln,OilRigHotel]];
		OilRigAlpha setVariable ["cti_town_neighbors",[OilRigBravo,OilRigCharlie,OilRigDelta]];
		OilRigBravo setVariable ["cti_town_neighbors",[OilRigAlpha,OilRigCharlie,GascoyneRidge]];
		OilRigCharlie setVariable ["cti_town_neighbors",[OilRigAlpha,OilRigBravo,OilRigDelta,DundeeBeach,DarwinPoint]];
		OilRigDelta setVariable ["cti_town_neighbors",[OilRigAlpha,OilRigCharlie,DarwinPoint,Darwin]];
		OilRigEcho setVariable ["cti_town_neighbors",[GrooteEylandt,Weipa]];
		OilRigFoxtrot setVariable ["cti_town_neighbors",[WindFarmAlpha,RockHampton]];
		OilRigGolf setVariable ["cti_town_neighbors",[Eden,Launceston]];
		OilRigHotel setVariable ["cti_town_neighbors",[WindFarmBravo,BassOutpost,KingIsland]];
		OilRigIndia setVariable ["cti_town_neighbors",[Albany,WindFarmBravo]];
		CapePeron setVariable ["cti_town_neighbors",[PortPerth,Albany]];
		PortPerth setVariable ["cti_town_neighbors",[CapePeron,Perth]];
		Perth setVariable ["cti_town_neighbors",[PortPerth,GascoyneOutpost]];
		PerthAirport setVariable ["cti_town_neighbors",[Perth,PerthAirport,OldFarm,Leonara]];
		OldFarm setVariable ["cti_town_neighbors",[PerthAirport,Albany,Nullabor,NullaborOutpost]];
		Albany setVariable ["cti_town_neighbors",[CapePeron,OldFarm,Nullabor,OilRigIndia]];
		Nullabor setVariable ["cti_town_neighbors",[Albany,OldFarm,GasDepot,NullaborOutpost]];
		NullaborOutpost setVariable ["cti_town_neighbors",[Nullabor,OldFarm,Leonara,GasDepot,SaltOutpost]];
		Leonara setVariable ["cti_town_neighbors",[PerthAirport,NullaborOutpost,GascoyneHeadwaters,LongBowl]];
		LongBowl setVariable ["cti_town_neighbors",[Leonara,Rift,SaltOutpost]];
		GascoyneOutpost setVariable ["cti_town_neighbors",[Perth,GascoyneHeadwaters,GascoyneRidge]];
		GascoyneHeadwaters setVariable ["cti_town_neighbors",[GascoyneOutpost,GascoyneRidge,WestAir,Leonara]];
		GascoyneRidge setVariable ["cti_town_neighbors",[OilRigBravo,GascoyneOutpost,GascoyneHeadwaters,WestAir]];
		WestAir setVariable ["cti_town_neighbors",[GascoyneRidge,GascoyneHeadwaters,DundeeBeach,Willare]];
		DundeeBeach setVariable ["cti_town_neighbors",[OilRigCharlie,WestAir]];
		Willare setVariable ["cti_town_neighbors",[WestAir,Rift,DustBowl,DarwinPoint]];
		Rift setVariable ["cti_town_neighbors",[Willare,LongBowl,SaltOutpost]];
		SaltOutpost setVariable ["cti_town_neighbors",[NullaborOutpost,Rift,LongBowl,UluruAir,SaltValley]];
		SaltValley setVariable ["cti_town_neighbors",[SaltOutpost,UluruAir,PineGap]];
		UluruAir setVariable ["cti_town_neighbors",[SaltOutpost,SaltValley,CooberPedy,PineGap]];
		PineGap setVariable ["cti_town_neighbors",[UluruAir,SaltValley,AliceSprings]];
		AliceSprings setVariable ["cti_town_neighbors",[IrwinsLair,PineGap,Junction,LakeEyre]];
		DustBowl setVariable ["cti_town_neighbors",[Willare,ThunderDome]];
		DarwinPoint setVariable ["cti_town_neighbors",[Darwin,OilRigCharlie,OilRigDelta,Willare]];
		ThunderDome setVariable ["cti_town_neighbors",[DustBowl,NorthernAir,Darwin]];
		Darwin setVariable ["cti_town_neighbors",[DarwinPoint,OilRigDelta,BootCamp,ThunderDome]];
		BootCamp setVariable ["cti_town_neighbors",[Darwin,VanDiemanGulf]];
		VanDiemanGulf setVariable ["cti_town_neighbors",[BootCamp,LightHousePoint]];
		LightHousePoint setVariable ["cti_town_neighbors",[VanDiemanGulf,GrooteEylandt]];
		QuickSand setVariable ["cti_town_neighbors",[GrooteEylandt,NorthernAir]];
		GrooteEylandt setVariable ["cti_town_neighbors",[LightHousePoint,QuickSand,OilRigEcho,MountIsa]];
		NorthernAir setVariable ["cti_town_neighbors",[ThunderDome,QuickSand,MountIsa]];
		Weipa setVariable ["cti_town_neighbors",[OilRigEcho,RadarOutpost]];
		RadarOutpost setVariable ["cti_town_neighbors",[Weipa,Cairns,WindFarmAlpha,MountIsa]];
		Cairns setVariable ["cti_town_neighbors",[RadarOutpost,WindFarmAlpha,RockHampton,BanditsHideOut]];
		BanditsHideOut setVariable ["cti_town_neighbors",[MountIsa,Cairns,SupportBase]];
		MountIsa setVariable ["cti_town_neighbors",[GrooteEylandt,NorthernAir,IrwinsLair,RadarOutpost,BanditsHideOut]];
		IrwinsLair setVariable ["cti_town_neighbors",[MountIsa,AliceSprings,Junction]];
		Junction setVariable ["cti_town_neighbors",[CrossRoads,IrwinsLair,AliceSprings]];
		CrossRoads setVariable ["cti_town_neighbors",[Toowoomba,Junction,BrokenHill]];
		GasDepot setVariable ["cti_town_neighbors",[Nullabor,NullaborOutpost,CooberPedy,PortLincoln]];
		CooberPedy setVariable ["cti_town_neighbors",[GasDepot,UluruAir,ProcessingPlant,Factory]];
		ProcessingPlant setVariable ["cti_town_neighbors",[LakeEyre,CooberPedy]];
		LakeEyre setVariable ["cti_town_neighbors",[AliceSprings,ProcessingPlant]];
		PortLincoln setVariable ["cti_town_neighbors",[WindFarmBravo,GasDepot,Factory,SpencerPoint]];
		SpencerPoint setVariable ["cti_town_neighbors",[PortLincoln,AdelaideAir]];
		Factory setVariable ["cti_town_neighbors",[CooberPedy,PortLincoln,BrokenHill,AdelaideAir]];
		AdelaideAir setVariable ["cti_town_neighbors",[SpencerPoint,Adelaide,Factory]];
		BrokenHill setVariable ["cti_town_neighbors",[Adelaide,Factory,SuperMax,CrossRoads]];
		Adelaide setVariable ["cti_town_neighbors",[AdelaideAir,TailemBend,BrokenHill]];
		TailemBend setVariable ["cti_town_neighbors",[Adelaide,Mildura,BassOutpost]];
		Mildura setVariable ["cti_town_neighbors",[TailemBend,Victoria]];
		SuperMax setVariable ["cti_town_neighbors",[BrokenHill,Toowoomba,Willcania]];
		Willcania setVariable ["cti_town_neighbors",[Toowoomba,SuperMax,ArmyBase,LumberYard]];
		SupportBase setVariable ["cti_town_neighbors",[BanditsHideOut,RockHampton,QueensBridge]];
		RockHampton setVariable ["cti_town_neighbors",[Cairns,OilRigFoxtrot,SupportBase,Brisbane]];
		Toowoomba setVariable ["cti_town_neighbors",[QueensBridge,CrossRoads,SuperMax,Willcania,Brisbane]];
		QueensBridge setVariable ["cti_town_neighbors",[SupportBase,Brisbane,Toowoomba]];
		Brisbane setVariable ["cti_town_neighbors",[RockHampton,BrisbaneSuburbs,QueensBridge,Toowoomba]];
		BrisbaneSuburbs setVariable ["cti_town_neighbors",[Brisbane,Quarry]];
		Quarry setVariable ["cti_town_neighbors",[BrisbaneSuburbs,ArmyBase,Sydney]];
		ArmyBase setVariable ["cti_town_neighbors",[Willcania,LumberYard,Quarry]];
		LumberYard setVariable ["cti_town_neighbors",[ArmyBase,Willcania,SydneyAir,Victoria]];
		Sydney setVariable ["cti_town_neighbors",[Quarry,SydneyAir]];
		SydneyAir setVariable ["cti_town_neighbors",[Sydney,LumberYard,Eden]];
		Eden setVariable ["cti_town_neighbors",[SydneyAir,Melbourne,PhillipPoint,OilRigGolf]];
		Victoria setVariable ["cti_town_neighbors",[LumberYard,Melbourne,Mildura]];
		Melbourne setVariable ["cti_town_neighbors",[Victoria,BassOutpost,PhillipPoint,Eden]];
		PhillipPoint setVariable ["cti_town_neighbors",[BassOutpost,Melbourne,Eden,KingIsland]];
		BassOutpost setVariable ["cti_town_neighbors",[OilRigHotel,TailemBend,PhillipPoint,Melbourne]];
		KingIsland setVariable ["cti_town_neighbors",[OilRigHotel,SmithtonDocks,PhillipPoint]];
		SmithtonDocks setVariable ["cti_town_neighbors",[TasmaniaAir,KingIsland,Launceston]];
		Launceston setVariable ["cti_town_neighbors",[OilRigGolf,Hobart,SmithtonDocks]];
		Hobart setVariable ["cti_town_neighbors",[Launceston,TasmaniaAir]];
		TasmaniaAir setVariable ["cti_town_neighbors",[Hobart,SmithtonDocks]];
	};
	case "mske": {
		RadarOutpost setVariable ["cti_town_neighbors", [EveronAir,Lamentin]];
		EveronAir setVariable ["cti_town_neighbors", [RadarOutpost,SaintPhillippe,WorkIsland]];
		SaintPhillippe setVariable ["cti_town_neighbors", [EveronAir,Meaux]];
		Meaux setVariable ["cti_town_neighbors", [SaintPhillippe,Tyrone]];
		Tyrone setVariable ["cti_town_neighbors", [Meaux,Gravette]];
		Gravette setVariable ["cti_town_neighbors", [Tyrone,Montignac]];
		Lamentin setVariable ["cti_town_neighbors", [RadarOutpost,Farm,LeMoule]];
		LeMoule setVariable ["cti_town_neighbors", [Farm,Lamentin,OutlookInn]];
		Farm setVariable ["cti_town_neighbors", [Montignac,Lamentin,LeMoule]];
		OutlookInn setVariable ["cti_town_neighbors", [LeMoule,Morton,CultIsland]];
		Morton setVariable ["cti_town_neighbors", [OutlookInn,Figari,Levie]];
		Figari setVariable ["cti_town_neighbors", [Morton,Provins]];
		Provins setVariable ["cti_town_neighbors", [Montignac,Figari,Chotain,Levie]];
		Montignac setVariable ["cti_town_neighbors", [Gravette,EntreDeux,Farm,Provins]];
		EntreDeux setVariable ["cti_town_neighbors", [Montignac,Chotain]];
		Military setVariable ["cti_town_neighbors", [EntreDeux,Military,Chotain,Cottage]];
		Chotain setVariable ["cti_town_neighbors", [Military,EntreDeux,Provins,Levie]];
		Levie setVariable ["cti_town_neighbors", [Morton,Chotain,Provins,CampLevie]];
		CampLevie setVariable ["cti_town_neighbors", [Levie,Regina,Durras]];
		Regina setVariable ["cti_town_neighbors", [CampLevie,Durras,CultIsland]];
		Durras setVariable ["cti_town_neighbors", [CampLevie,Regina,DurrasRadar,Vernon]];
		DurrasRadar setVariable ["cti_town_neighbors", [Durras]];
		Vernon setVariable ["cti_town_neighbors", [Durras,SaintPierre]];
		SaintPierre setVariable ["cti_town_neighbors", [Vernon,USSFREEDOM]];
		CultIsland setVariable ["cti_town_neighbors", [OutlookInn,Regina,DeathAir]];
		DeathAir setVariable ["cti_town_neighbors", [CultIsland,Lolisse,Groisse,Arette]];
		Lolisse setVariable ["cti_town_neighbors", [DeathAir,Groisse,MaldenFuel]];
		MaldenFuel setVariable ["cti_town_neighbors", [Lolisse,MaldenAirport]];
		MaldenAirport setVariable ["cti_town_neighbors", [MaldenFuel,SaintLouis,USSFREEDOM]];
		SaintLouis setVariable ["cti_town_neighbors", [MaldenAirport,Larche,LaTrinite]];
		Larche setVariable ["cti_town_neighbors", [SaintLouis,Homestead]];
		LaTrinite setVariable ["cti_town_neighbors", [SaintLouis,Dourdan,SaintLouis]];
		LaPassagne setVariable ["cti_town_neighbors", [Quarry,Arette,LaRiviere]];
		Groisse setVariable ["cti_town_neighbors", [DeathAir,Lolisse,Homestead,LaPassagne]];
		Homestead setVariable ["cti_town_neighbors", [Larche,Groisse,Quarry]];
		Quarry setVariable ["cti_town_neighbors", [Homestead,Arudy,LaPassagne]];
		Arudy setVariable ["cti_town_neighbors", [Homestead,Quarry,Dourdan]];
		Dourdan setVariable ["cti_town_neighbors", [Arudy,Houdan,LaTrinite]];
		Houdan setVariable ["cti_town_neighbors", [Dourdan,Laport,SainteMarie]];
		Arette setVariable ["cti_town_neighbors", [LaPassagne,Faro,DeathAir,LaRiviere]];
		Faro setVariable ["cti_town_neighbors", [Arette,Lighthouse]];
		LaRiviere setVariable ["cti_town_neighbors", [Arette,LaPassagne,Cancon]];
		Lighthouse setVariable ["cti_town_neighbors", [Faro,Cancon]];
		Cancon setVariable ["cti_town_neighbors", [Lighthouse,LaRiviere,Chapoi]];
		Chapoi setVariable ["cti_town_neighbors", [Cancon,SainteMarie,Laport]];
		SainteMarie setVariable ["cti_town_neighbors", [Chapoi,Houdan]];
		Laport setVariable ["cti_town_neighbors", [Chapoi,Houdan,MiltaryBase]];
		MiltaryBase setVariable ["cti_town_neighbors", [Laport,FuelPoint]];
		FuelPoint setVariable ["cti_town_neighbors", [MiltaryBase,WindFarm]];
		WindFarm setVariable ["cti_town_neighbors", [FuelPoint,Kulmuska,WorkCamp]];
		USSFREEDOM setVariable ["cti_town_neighbors", [VelikayaPoint,ParadiseIsland,MaldenAirport,SaintPierre,Lebrija]];
		VelikayaPoint setVariable ["cti_town_neighbors", [Velikaya,ParadiseIsland,USSFREEDOM]];
		Velikaya setVariable ["cti_town_neighbors", [WorkCamp,VelikayaPoint,Hotzenplotz,Gabnavolok]];
		WorkCamp setVariable ["cti_town_neighbors", [WindFarm,Velikaya,Kulmuska]];
		KulmuskaAir setVariable ["cti_town_neighbors", [SupplyBase,PortFreedom,Kulmuska]];
		SupplyBase setVariable ["cti_town_neighbors", [OilRig,MemphisBelle,PortOshta,KulmuskaAir]];
		MemphisBelle setVariable ["cti_town_neighbors", [SupplyBase,Silola]];
		Kulmuska setVariable ["cti_town_neighbors", [KulmuskaAir,WorkCamp,WindFarm]];
		Silola setVariable ["cti_town_neighbors", [MemphisBelle,Froburg,Hotzenplotz]];
		Froburg setVariable ["cti_town_neighbors", [MemphisBelle,Silola,Ridgeline]];
		Hotzenplotz setVariable ["cti_town_neighbors", [Silola,Velikaya,Gabnavolok]];
		Gabnavolok setVariable ["cti_town_neighbors", [Velikaya,Hotzenplotz,ParadiseIsland,CampOshta]];
		Ridgeline setVariable ["cti_town_neighbors", [CampOshta,Froburg]];
		CampOshta setVariable ["cti_town_neighbors", [Ridgeline,Oshta,Gabnavolok]];
		PortOshta setVariable ["cti_town_neighbors", [OilRig,SupplyBase,LadvaVetka]];
		Oshta setVariable ["cti_town_neighbors", [CampOshta,LadvaVetka,Voskovo,Voskovo,Retreat]];
		LadvaVetka setVariable ["cti_town_neighbors", [Oshta,PortOshta]];
		Voskovo setVariable ["cti_town_neighbors", [Oshta,Retreat]];
		OilRig setVariable ["cti_town_neighbors", [RadarStation,PortOshta,SupplyBase]];
		RadarStation setVariable ["cti_town_neighbors", [PortFreedom,OilRig]];
		PortFreedom setVariable ["cti_town_neighbors", [RadarStation,KulmuskaAir]];
		ParadiseIsland setVariable ["cti_town_neighbors", [Gabnavolok,VelikayaPoint,Retreat,USSFREEDOM,Resort]];
		Retreat setVariable ["cti_town_neighbors", [ParadiseIsland,Voskovo,Oshta,Stronghold]];
		WorkIsland setVariable ["cti_town_neighbors", [MilitaryAirport,Cottage,EveronAir]];
		Cottage setVariable ["cti_town_neighbors", [MilitaryAirport,WorkIsland,PowerStation,Military]];
		MilitaryAirport setVariable ["cti_town_neighbors", [MilitaryHospital,MilitaryTrainCenter,Cottage,WorkIsland]];
		MilitaryHospital setVariable ["cti_town_neighbors", [MilitaryTrainCenter,NorthHarbor,MilitaryAirport]];
		MilitaryTrainCenter setVariable ["cti_town_neighbors", [Begost,MilitaryHospital,MilitaryAirport]];
		NorthHarbor setVariable ["cti_town_neighbors", [ComPlatform,MilitaryHospital,Begost]];
		Begost setVariable ["cti_town_neighbors", [MilitaryOutpost,PowerStation,MilitaryTrainCenter,Border,NorthHarbor]];
		PowerStation setVariable ["cti_town_neighbors", [RadioMeridan,MilitaryOutpost,Begost,Cottage]];
		MilitaryOutpost setVariable ["cti_town_neighbors", [RadioMeridan,Border,PowerStation,Begost]];
		Border setVariable ["cti_town_neighbors", [Belnuevo,Jarna,MilitaryOutpost,Begost]];
		RadioMeridan setVariable ["cti_town_neighbors", [MeridanMilitary,Lebrija,MilitaryOutpost,PowerStation]];
		Lebrija setVariable ["cti_town_neighbors", [USSFREEDOM,RadioMeridan,MeridanMilitary]];
		MeridanMilitary setVariable ["cti_town_neighbors", [Lebrija,RadioMeridan,Resort]];
		Resort setVariable ["cti_town_neighbors", [ParadiseIsland,MeridanMilitary,SaintRenoir]];
		SaintRenoir setVariable ["cti_town_neighbors", [Resort,Belnuevo,SanAlto]];
		Belnuevo setVariable ["cti_town_neighbors", [SaintRenoir,Border,Jarna]];
		Jarna setVariable ["cti_town_neighbors", [Belnuevo,SaintBieuc,Border,Tormes]];
		Boulade setVariable ["cti_town_neighbors", [Tormes,ComPlatform]];
		Tormes setVariable ["cti_town_neighbors", [Jarna,Internia,Boulade]];
		SaintBieuc setVariable ["cti_town_neighbors", [Jarna,Internia]];
		Internia setVariable ["cti_town_neighbors", [SaintBieuc,Tormes,Vadora]];
		SanAlto setVariable ["cti_town_neighbors", [SaintRenoir,Stronghold,Hilltop]];
		Stronghold setVariable ["cti_town_neighbors", [Retreat,SanAlto,SarugoAirport]];
		Hilltop setVariable ["cti_town_neighbors", [SanAlto,Vadora]];
		Vadora setVariable ["cti_town_neighbors", [Hilltop,SarugoAirport,EastHarbor,LeFrimme,Internia]];
		LeFrimme setVariable ["cti_town_neighbors", [ComPlatform,Vadora]];
		ComPlatform setVariable ["cti_town_neighbors", [Boulade,LeFrimme,NorthHarbor]];
		SarugoAirport setVariable ["cti_town_neighbors", [Stronghold,EastHarbor,Vadora]];
 		EastHarbor setVariable ["cti_town_neighbors", [SarugoAirport,Vadora]];
	};
	case "lingor3": {
		Fantasmo setVariable ["cti_town_neighbors", [OldBritishFort,Chupinka]];
		SubPen setVariable ["cti_town_neighbors", [OldBritishFort,Maruko,Conoteta]];
		Corazon setVariable ["cti_town_neighbors", [Prospero,Maruko,Victorin,SanArulco,Tucos]];
		Prospero setVariable ["cti_town_neighbors", [Corazon,Faunaverde,Lagosa,Victorin]];
		Montehofo setVariable ["cti_town_neighbors", [Faunaverde,Bilbado,MtPeligra,Matacan]];
		Calamar setVariable ["cti_town_neighbors", [Lagosa,Bilbado,Matacan,FuelDepot]];
		FuelDepot setVariable ["cti_town_neighbors", [Calamar,Medlina,Chupinka]];
		Chupinka setVariable ["cti_town_neighbors", [FuelDepot,ElVillon,Fantasmo]];
		Maruko setVariable ["cti_town_neighbors", [Corazon,SubPen,Conoteta,SanIsabel,Tucos]];
		Conoteta setVariable ["cti_town_neighbors", [Maruko,SubPen,WindFarm]];
		Bilbado setVariable ["cti_town_neighbors", [Montehofo,Calamar,Faunaverde,Lagosa,Matacan]];
		Matacan setVariable ["cti_town_neighbors", [Calamar,Bilbado,Drassen,Montehofo]];
		Drassen setVariable ["cti_town_neighbors", [Matacan,Medlina,BSFMarika]];
		Medlina setVariable ["cti_town_neighbors", [FuelDepot,Drassen]];
		Chupinka setVariable ["cti_town_neighbors", [FuelDepot,ElVillon,Fantasmo]];
		ElVillon setVariable ["cti_town_neighbors", [Chupinka,Victorin,Lagosa]];
		Victorin setVariable ["cti_town_neighbors", [Corazon,Prospero,ElVillon]];
		Lagosa setVariable ["cti_town_neighbors", [Calamar,Bilbado,Faunaverde,Prospero,ElVillon]];
		Faunaverde setVariable ["cti_town_neighbors", [Lagosa,Prospero,Montehofo,Bilbado]];
		MotodromComplex setVariable ["cti_town_neighbors", [MtPeligra,NewBenio,Vidora,BSFMarika]];
		OldBritishFort setVariable ["cti_town_neighbors", [SubPen,Fantasmo]];
		MtPeligra setVariable ["cti_town_neighbors", [MotodromComplex,Montehofo,SanArulco]];
		Vidora setVariable ["cti_town_neighbors", [Fernando,MotodromComplex,SanArulco,NewBenio]];
		NewBenio setVariable ["cti_town_neighbors", [MotodromComplex,Vidora,BSFMarika,Zanjeer]];
		Fernando setVariable ["cti_town_neighbors", [Vidora,Tucos,ResearchLab101,Prison]];
		Tucos setVariable ["cti_town_neighbors", [Fernando,ResearchLab101,Maruko,Corazon]];
		ResearchLab101 setVariable ["cti_town_neighbors", [SanIsabel,Tucos,Fernando,Hill63]];
		SanIsabel setVariable ["cti_town_neighbors", [Hill63,Maruko]];
		Hill63 setVariable ["cti_town_neighbors", [SanIsabel,Prison,Gatoro,MockVillageTango,ResearchLab101]];
		Prison setVariable ["cti_town_neighbors", [Fernando,Zanjeer,Arapesca,Medicolin,Hill63]];
		Zanjeer setVariable ["cti_town_neighbors", [Prison,Arapesca,NewBenio]];
		Arapesca setVariable ["cti_town_neighbors", [Zanjeer,Medicolin,Prison,AeropuertoMirasol]];
		Medicolin setVariable ["cti_town_neighbors", [Prison,Gatoro,Arapesca,AeropuertoMirasol]];
		Gatoro setVariable ["cti_town_neighbors", [Hill63,Medicolin,MockVillageTango]];
		SanArulco setVariable ["cti_town_neighbors", [Vidora,Corazon,MtPeligra,Tucos]];
		AeropuertoMirasol setVariable ["cti_town_neighbors", [Arapesca,Medicolin]];
		WindFarm setVariable ["cti_town_neighbors", [Conoteta,MockVillageVictor]];
		MockVillageVictor setVariable ["cti_town_neighbors", [WindFarm,MockVillageTango]];
		MockVillageTango setVariable ["cti_town_neighbors", [MockVillageVictor,Gatoro,Hill63]];
		BSFMarika setVariable ["cti_town_neighbors", [Drassen,MotodromComplex,NewBenio]];
	}; 
	case "dingor": {
		Fantasmo setVariable ["cti_town_neighbors", [OldBritishFort,Chupinka]];
		SubPen setVariable ["cti_town_neighbors", [OldBritishFort,Maruko,Conoteta]];
		Corazon setVariable ["cti_town_neighbors", [Prospero,Maruko,Victorin,SanArulco,Tucos]];
		Prospero setVariable ["cti_town_neighbors", [Corazon,Faunaverde,Lagosa,Victorin]];
		Montehofo setVariable ["cti_town_neighbors", [Faunaverde,Bilbado,MtPeligra,Matacan]];
		Calamar setVariable ["cti_town_neighbors", [Lagosa,Bilbado,Matacan,FuelDepot]];
		FuelDepot setVariable ["cti_town_neighbors", [Calamar,Medlina,Chupinka]];
		Chupinka setVariable ["cti_town_neighbors", [FuelDepot,ElVillon,Fantasmo]];
		Maruko setVariable ["cti_town_neighbors", [Corazon,SubPen,Conoteta,SanIsabel,Tucos]];
		Conoteta setVariable ["cti_town_neighbors", [Maruko,SubPen,WindFarm]];
		Bilbado setVariable ["cti_town_neighbors", [Montehofo,Calamar,Faunaverde,Lagosa,Matacan]];
		Matacan setVariable ["cti_town_neighbors", [Calamar,Bilbado,Drassen,Montehofo]];
		Drassen setVariable ["cti_town_neighbors", [Matacan,Medlina,Benio]];
		Medlina setVariable ["cti_town_neighbors", [FuelDepot,Drassen]];
		Chupinka setVariable ["cti_town_neighbors", [FuelDepot,ElVillon,Fantasmo]];
		ElVillon setVariable ["cti_town_neighbors", [Chupinka,Victorin,Lagosa]];
		Victorin setVariable ["cti_town_neighbors", [Corazon,Prospero,ElVillon]];
		Lagosa setVariable ["cti_town_neighbors", [Calamar,Bilbado,Faunaverde,Prospero,ElVillon]];
		Faunaverde setVariable ["cti_town_neighbors", [Lagosa,Prospero,Montehofo,Bilbado]];
		MotodromComplex setVariable ["cti_town_neighbors", [MtPeligra,Benio,Vidora]];
		OldBritishFort setVariable ["cti_town_neighbors", [SubPen,Fantasmo]];
		MtPeligra setVariable ["cti_town_neighbors", [MotodromComplex,Montehofo,SanArulco]];
		Vidora setVariable ["cti_town_neighbors", [Fernando,MotodromComplex,SanArulco,Benio]];
		Benio setVariable ["cti_town_neighbors", [MotodromComplex,Vidora,Drassen,Zanjeer]];
		Fernando setVariable ["cti_town_neighbors", [Vidora,Tucos,ResearchLab101,Prison]];
		Tucos setVariable ["cti_town_neighbors", [Fernando,ResearchLab101,Maruko,Corazon]];
		ResearchLab101 setVariable ["cti_town_neighbors", [SanIsabel,Tucos,Fernando,Hill63]];
		SanIsabel setVariable ["cti_town_neighbors", [Tucos,Hill63,Maruko]];
		Hill63 setVariable ["cti_town_neighbors", [SanIsabel,Prison,Gatoro,WindFarm,ResearchLab101]];
		Prison setVariable ["cti_town_neighbors", [Fernando,Zanjeer,Arapesca,Medicolin,Hill63]];
		Zanjeer setVariable ["cti_town_neighbors", [Prison,Arapesca,Benio]];
		Arapesca setVariable ["cti_town_neighbors", [Zanjeer,Medicolin,Prison,ComPlatform]];
		Medicolin setVariable ["cti_town_neighbors", [Prison,Gatoro,Arapesca,ComPlatform]];
		Gatoro setVariable ["cti_town_neighbors", [Hill63,Medicolin,WindFarm]];
		SanArulco setVariable ["cti_town_neighbors", [Vidora,Corazon,MtPeligra,Tucos]];
		ComPlatform setVariable ["cti_town_neighbors", [Arapesca,Medicolin,WindFarm]];
		WindFarm setVariable ["cti_town_neighbors", [Conoteta,Gatoro,Hill63,ComPlatform]];
	};
	case "tembelan": {
		DicuriRusak setVariable ["cti_town_neighbors", [FuelDepot,Ekspor,PengolahanIndustrial,Parit,Terangkat]];
		Ekspor setVariable ["cti_town_neighbors", [DicuriRusak,PengolahanIndustrial,Parit]];
		PengolahanIndustrial setVariable ["cti_town_neighbors", [Ekspor,SegiTiga,DicuriRusak,Terangkat]];
		SegiTiga setVariable ["cti_town_neighbors", [PengolahanIndustrial,SelatanMilitaryAirbase,Terangkat,TepiPantaiResort]];
		SelatanMilitaryAirbase setVariable ["cti_town_neighbors", [SegiTiga,ComPlatform,FuelDepot,Terangkat]];
		FuelDepot setVariable ["cti_town_neighbors", [DicuriRusak,SelatanMilitaryAirbase,KumuhPersegi,Terangkat]];
		ComPlatform setVariable ["cti_town_neighbors", [SelatanMilitaryAirbase,YuriIsland,TepiPantaiResort,KasurIsland]];
		YuriIsland setVariable ["cti_town_neighbors", [ComPlatform]];
		Parit setVariable ["cti_town_neighbors", [DicuriRusak,Ekspor,KumuhPersegi,PowerStation]];
		KumuhPersegi setVariable ["cti_town_neighbors", [WindFarm,Parit,FuelDepot,PowerStation,Lalat]];
		PowerStation setVariable ["cti_town_neighbors", [Lalat,KumuhPersegi,Gereja,ConstructionSite,Parit,Ekspor]];
		WindFarm setVariable ["cti_town_neighbors", [Lalat,KumuhPersegi,SendirianGereja,TerlupakanKastil,DitolakDesa]];
		Lalat setVariable ["cti_town_neighbors", [PowerStation,KumuhPersegi,ConstructionSite,WindFarm,SendirianGereja]];
		Gereja setVariable ["cti_town_neighbors", [PowerStation,ConstructionSite,Ekspor,LapanganFustal]];
		ConstructionSite setVariable ["cti_town_neighbors", [PowerStation,LapanganFustal,Lalat,Gereja,SendirianGereja]];
		LapanganFustal setVariable ["cti_town_neighbors", [ConstructionSite,SendirianGereja,Gereja,LapanganFustalIndustrial,PohonLumberCamp]];
		SendirianGereja setVariable ["cti_town_neighbors", [LapanganFustal,Lalat,WindFarm,LapanganFustalIndustrial,TerlupakanKastil,ConstructionSite]];
		Hill357 setVariable ["cti_town_neighbors", [TerlupakanKastil,SendirianGereja,LapanganFustalIndustrial,RusakIman]];
		TerlupakanKastil setVariable ["cti_town_neighbors", [Hill357,WindFarm,SendirianGereja,DitolakDesa]];
		Terangkat setVariable ["cti_town_neighbors", [FuelDepot,SelatanMilitaryAirbase,SegiTiga,PengolahanIndustrial,DicuriRusak]];
		DitolakDesa setVariable ["cti_town_neighbors", [WindFarm,TerlupakanKastil,Pertemuan,IkanKota]];
		Pertemuan setVariable ["cti_town_neighbors", [DitolakDesa,IkanKota,Tertutup,KasurIsland]];
		LapanganFustalIndustrial setVariable ["cti_town_neighbors", [LapanganFustal,SendirianGereja,Hill357,RusakIman,TokoTempat,PohonLumberCamp]];
		IkanKota setVariable ["cti_town_neighbors", [Pertemuan,DitolakDesa,TerlupakanKastil,Tertutup,RusakIman]];
		Tertutup setVariable ["cti_town_neighbors", [IkanKota,Pertemuan,RusakIman,Bangunan]];
		RusakIman setVariable ["cti_town_neighbors", [Tertutup,IkanKota,Hill357,LapanganFustalIndustrial,DesaIkan,TokoTempat]];
		DesaIkan setVariable ["cti_town_neighbors", [RusakIman,Bangunan,Bagain,BesarAirbase,TokoTempat,Hutankedua]];
		Bangunan setVariable ["cti_town_neighbors", [Bagain,DesaIkan,Tertutup,RusakIman,KasurIsland]];
		BesarAirbase setVariable ["cti_town_neighbors", [Bagain,DesaIkan,TepiPantaiResortAirfield,Hutankedua,DesaIkan]];
		Bagain setVariable ["cti_town_neighbors", [KasurIsland,BesarAirbase,Bangunan,DesaIkan,Hutankedua]];
		KasurIsland setVariable ["cti_town_neighbors", [Bagain,ComPlatform,Pertemuan,Bangunan]];
		TokoTempat setVariable ["cti_town_neighbors", [RusakIman,DesaIkan,LapanganFustalIndustrial,PohonLumberCamp,Hutankedua]];
		PohonLumberCamp setVariable ["cti_town_neighbors", [TokoTempat,LapanganFustal,LapanganFustalIndustrial,IstirahatAkhir,Hutankedua]];
		Hutankedua setVariable ["cti_town_neighbors", [PohonLumberCamp,TokoTempat,IstirahatAkhir,TepiPantaiResortAirfield,BesarAirbase]];
		IstirahatAkhir setVariable ["cti_town_neighbors", [PohonLumberCamp,Hutankedua,TepiPantaiResortAirfield]];
		TepiPantaiResortAirfield setVariable ["cti_town_neighbors", [IstirahatAkhir,Hutankedua,TepiPantaiResort,BesarAirbase]];
		TepiPantaiResort setVariable ["cti_town_neighbors", [TepiPantaiResortAirfield,ComPlatform,SegiTiga]];
	};
	case "deniland": {
		Popinchi setVariable ["cti_town_neighbors", [Dolac,Ziginovo,Marijas]];
		Dolac setVariable ["cti_town_neighbors", [Popinchi,Suvagora,Ziginovo,Degmanovacdonji]];
		Ziginovo setVariable ["cti_town_neighbors", [Dolac,Popinchi,Degmanovacdonji,Petnica]];
		Degmanovacdonji setVariable ["cti_town_neighbors", [Ziginovo,Dolac,Degmanovagornji,Petnica]];
		Degmanovagornji setVariable ["cti_town_neighbors", [Degmanovacdonji,Novograd,Suvagora,Rudnica]];
		Petnica setVariable ["cti_town_neighbors", [Degmanovacdonji,Ziginovo,Novograd,Rakari,Stajevo]];
		Rudnica setVariable ["cti_town_neighbors", [Degmanovagornji,Novograd,Zutikamen,Gradac,Suvagora]];
		Suvagora setVariable ["cti_town_neighbors", [Dolac,Krupac,Rudnica,Degmanovagornji,Gradac]];
		Krupac setVariable ["cti_town_neighbors", [Gradac,Bokigrad,Suvagora]];
		Gradac setVariable ["cti_town_neighbors", [Krupac,Suvagora,Rudnica,Rudnjak,Zutikamen,Bokigrad]];
		Novograd setVariable ["cti_town_neighbors", [Vrapci,Degmanovagornji,Zutikamen,Rudnica,DonjaBoranja,TreePlantation,Petnica]];
		Rakari setVariable ["cti_town_neighbors", [Stajevo,Bukoviste,Petnica]];
		TreePlantation setVariable ["cti_town_neighbors", [Novograd,Kamendol,Markograd,Bukoviste,Vrapci,Koritnik]];
		Bokigrad setVariable ["cti_town_neighbors", [Marijas,Krupac,Ivanje,Gradac,Rudnjak,Rajac,Mokrin]];
		Marijas setVariable ["cti_town_neighbors", [Bokigrad,Rajac,Popinchi]];
		Rajac setVariable ["cti_town_neighbors", [Marijas,Mokrin,Arminovac,AirportNorth,WindFarm,Bokigrad]];
		Arminovac setVariable ["cti_town_neighbors", [Rajac,WindFarm,Mokrin,Rakovica]];
		Mokrin setVariable ["cti_town_neighbors", [Arminovac,Ivanje,GornjiDolac,Rakovica,Bokigrad,Rajac]];
		Ivanje setVariable ["cti_town_neighbors", [Mokrin,Bokigrad,Bare,Rudnjak]];
		Bare setVariable ["cti_town_neighbors", [Ivanje,GornjiDolac,Ivanje,Rudnjak,Jablanica,Topola]];
		Jablanica setVariable ["cti_town_neighbors", [Bare,Topola,Tresnjic,Rudnjak,NovoOrloviste]];
		Rudnjak setVariable ["cti_town_neighbors", [Bare,Jablanica,Zutikamen,Ivanje,Gradac,Bokigrad]];
		Zutikamen setVariable ["cti_town_neighbors", [Rudnjak,Novograd,Gradac,Rudnica,DonjaBoranja]];
		WindFarm setVariable ["cti_town_neighbors", [AirportNorth,Arminovac,Rajac,BizzaroStapar]];
		Bukoviste setVariable ["cti_town_neighbors", [Rakari,Stajevo,Markograd,TreePlantation]];
		Stajevo setVariable ["cti_town_neighbors", [Bukoviste,Rakari,Petnica,Markograd,CultIsland]];
		CultIsland setVariable ["cti_town_neighbors", [ComPlatform,Stajevo,Belin]];
		ComPlatform setVariable ["cti_town_neighbors", [CultIsland,USSFREEDOM]];
		USSFREEDOM setVariable ["cti_town_neighbors", [ComPlatform,WreckIsland,OilRig]];
		OilRig setVariable ["cti_town_neighbors", [WreckIsland,USSFREEDOM,Vrba]];
		WreckIsland setVariable ["cti_town_neighbors", [USSFREEDOM,OilRig,Backovac]];
		Markograd setVariable ["cti_town_neighbors", [Bukoviste,Stajevo,TreePlantation,Titograd]];
		Vrapci setVariable ["cti_town_neighbors", [Novograd,DonjaBoranja,TreePlantation,Kamendol]];
		Titograd setVariable ["cti_town_neighbors", [Markograd,Koritnik,Belin]];
		Belin setVariable ["cti_town_neighbors", [Titograd,CultIsland,Backovac]];
		Koritnik setVariable ["cti_town_neighbors", [Titograd,TreePlantation,Kamendol,Nehruovci,CrnaBara]];
		Kamendol setVariable ["cti_town_neighbors", [TreePlantation,Vrapci,Koritnik,Nehruovci,Jabukovac,DonjaBoranja]];
		DonjaBoranja setVariable ["cti_town_neighbors", [Vrapci,Kamendol,ZutiKamen,Novograd,Tresnjic,Jabukovac]];
		Nehruovci setVariable ["cti_town_neighbors", [Koritnik,Kamendol,Jabukovac,TookateeVillage,CrnaBara]];
		Jabukovac setVariable ["cti_town_neighbors", [Kamendol,DonjaBoranja,Tresnjic,Nehruovci]];
		Tresnjic setVariable ["cti_town_neighbors", [Jabukovac,Stevac,Jablanica,DonjaBoranja]];
		Stevac setVariable ["cti_town_neighbors", [Tresnjic,NovoOrloviste,Babine]];
		NovoOrloviste setVariable ["cti_town_neighbors", [Stevac,Topola,Sirogojno,Jablanica,Fuxin]];
		Topola setVariable ["cti_town_neighbors", [NovoOrloviste,Vranovo,Sirogojno,GornjiDolac,Bare,Jablanica]];
		Sirogojno setVariable ["cti_town_neighbors", [Topola,Vranovo,Mramor,Fuxin,NovoOrloviste]];
		Vranovo setVariable ["cti_town_neighbors", [NoviBrest,Sirogojno,Topola,GornjiDolac,Mramor,Rakovica]];
		GornjiDolac setVariable ["cti_town_neighbors", [Vranovo,Topola,Bare,Rakovica,Mokrin]];
		Rakovica setVariable ["cti_town_neighbors", [GornjiDolac,Arminovac,Izgubici,BizzaroStapar,NoviBrest,Vranovo,Mokrin]];
		NoviBrest setVariable ["cti_town_neighbors", [Vranovo,Stapar,Japaga,Mramor,Izgubici,Rakovica]];
		Mramor setVariable ["cti_town_neighbors", [Dencity,NoviBrest,Sirogojno,Japaga,Vranovo]];
		Dencity setVariable ["cti_town_neighbors", [Mramor,Mandre,Hitmadin]];
		Japaga setVariable ["cti_town_neighbors", [Stapar,NoviBrest,Mramor,Pickovac]];
		Stapar setVariable ["cti_town_neighbors", [Japaga,Izgubici,NoviBrest]];
		Izgubici setVariable ["cti_town_neighbors", [Stapar,Divci,Rakovica,BizzaroStapar,NoviBrest]];
		BizzaroStapar setVariable ["cti_town_neighbors", [AirportNorth,Divci,Izgubici,WindFarm,Rakovica]];
		Divci setVariable ["cti_town_neighbors", [AirportNorth,Izgubici,BizzaroStapar]];
		AirportNorth setVariable ["cti_town_neighbors", [WindFarm,BizzaroStapar,Divci,Rajac]];
		Vrba setVariable ["cti_town_neighbors", [OilRig,Acidovac,Backovac]];
		Backovac setVariable ["cti_town_neighbors", [WreckIsland,Visokopolje,Belin,Crnabara,Vrba]];
		Acidovac setVariable ["cti_town_neighbors", [Calije,Babindonji,Vrba]];
		Calije setVariable ["cti_town_neighbors", [Acidovac,Glisici,Treskovac]];
		Babindonji setVariable ["cti_town_neighbors", [Babingornji,Acidovac,Kiseljak]];
		Babingornji setVariable ["cti_town_neighbors", [Babindonji,Kiseljak,Vulesin,Treskovac,Lutonovac]];
		Glisici setVariable ["cti_town_neighbors", [Visokopolje,Treskovac,Calije,Suburb]];
		Treskovac setVariable ["cti_town_neighbors", [Glisici,Calije,Vulesin,Suburb,Babingornji]];
		Visokopolje setVariable ["cti_town_neighbors", [Glisici,Backovac,CrnaBara,Suburb]];
		CrnaBara setVariable ["cti_town_neighbors", [Visokopolje,Backovac,Koritnik,Suburb,Nehruovci]];
		Suburb setVariable ["cti_town_neighbors", [Visokopolje,CrnaBara,Malastena,Velikabukva,Treskovac,Glisici,TookateeVillage]];
		Vulesin setVariable ["cti_town_neighbors", [Treskovac,Velikastena,Lutonovac,Kamenovac,Babingornji]];
		Lutonovac setVariable ["cti_town_neighbors", [Sakalovac,Vulesin,Babingornji,AirportSouth]];
		Malastena setVariable ["cti_town_neighbors", [Suburb,Velikastena,Velikabukva,VelikiMrav]];
		Velikastena setVariable ["cti_town_neighbors", [Malastena,Kamenovac,Vulesin,VelikiMrav]];
		Bukvic setVariable ["cti_town_neighbors", [Kiseljak,AirportSouth,CampApollo]];
		AirportSouth setVariable ["cti_town_neighbors", [Sakalovac,Bukvic,Lutonovac,Kiseljak]];
		Kiseljak setVariable ["cti_town_neighbors", [Bukvic,AirportSouth,Babingornji,Babindonji]];
		Sakalovac setVariable ["cti_town_neighbors", [Lutonovac,AirportSouth,Kamenovac,RoadTunnelCheckpoint]];
		Velikabukva setVariable ["cti_town_neighbors", [WindmillHill,VelikiMrav,Suburb,Malastena,Babine,TookateeVillage]];
		TookateeVillage setVariable ["cti_town_neighbors", [Velikabukva,Nehruovci,Babine,Suburb]];
		Kamenovac setVariable ["cti_town_neighbors", [Velikastena,Sakalovac,Crnopolje,VelikiMrav,Vulesin]];
		Crnopolje setVariable ["cti_town_neighbors", [Kamenovac,Denivci,RoadTunnelCheckpoint]];
		Denivci setVariable ["cti_town_neighbors", [Crnopolje,VelikiMrav,Stenovac,Kalna]];
		RoadTunnelCheckpoint setVariable ["cti_town_neighbors", [Crnopolje,CampApollo,Kalna,Sakalovac]];
		CampApollo setVariable ["cti_town_neighbors", [RoadTunnelCheckpoint,Bukvic,Rabrovo]];
		Stenovac setVariable ["cti_town_neighbors", [VelikiMrav,Necici,Kalna,Denivci]];
		Necici setVariable ["cti_town_neighbors", [VelikiMrav,Stenovac,Dvorane,WindmillHill]];
		VelikiMrav setVariable ["cti_town_neighbors", [Denivci,Kamenovac,Necici,Stenovac,Velikabukva,Velikastena,WindmillHill,Malastena]];
		Kalna setVariable ["cti_town_neighbors", [Stenovac,Javorje,Kuti,RoadTunnelCheckpoint,Denivci]];
		Dvorane setVariable ["cti_town_neighbors", [Necici,Belovgrad,VelikiDol,WindmillHill]];
		Javorje setVariable ["cti_town_neighbors", [Kalna,Kuti,VelikiDol]];
		Kuti setVariable ["cti_town_neighbors", [Javorje,Kalna,Busur]];
		VelikiDol setVariable ["cti_town_neighbors", [Javorje,Dvorane,WorkCamp]];
		Busur setVariable ["cti_town_neighbors", [Kuti,Rabrovo]];
		WorkCamp setVariable ["cti_town_neighbors", [Rabrovo,Pickovac,VelikiDol]];
		Rabrovo setVariable ["cti_town_neighbors", [WorkCamp,Busur,CampApollo]];
		Belovgrad setVariable ["cti_town_neighbors", [Pickovac,Dvorane,Novoselo,Hitmadin]];
		Pickovac setVariable ["cti_town_neighbors", [Belovgrad,WorkCamp,Hitmadin,Japaga]];
		Novoselo setVariable ["cti_town_neighbors", [Belovgrad,Fuxin,WindmillHill,Mandre,Hitmadin]];
		Fuxin setVariable ["cti_town_neighbors", [Novoselo,Mandre,Babine,WindmillHill,NovoOrloviste,Sirogojno]];
		Mandre setVariable ["cti_town_neighbors", [Fuxin,Hitmadin,Novoselo,Dencity]];
		Hitmadin setVariable ["cti_town_neighbors", [Mandre,Dencity,Pickovac,Belovgrad,Novoselo]];
		Babine setVariable ["cti_town_neighbors", [WindmillHill,Fuxin,Velikabukva,Stevac,TookateeVillage]];
		WindmillHill setVariable ["cti_town_neighbors", [Fuxin,Babine,Novoselo,Necici,Velikabukva,Dvorane,VelikiMrav]];
	};
	case "fallujah": {
		FOB setVariable ["cti_town_neighbors", [Mualimeen,Highway11]];
		Mualimeen setVariable ["cti_town_neighbors", [FOB,Askari,Jolan]];
		Jolan setVariable ["cti_town_neighbors", [Mualimeen,Askari,Resafa,Sinai]];
		Askari setVariable ["cti_town_neighbors", [Mualimeen,Jolan,Industrial_Park]];
		Resafa setVariable ["cti_town_neighbors", [Jolan,Sinai,Fallujah_Barrage]];
		Sinai setVariable ["cti_town_neighbors", [Resafa,Industrial_Park,Fallujah_Barrage]];
		Fallujah_Barrage setVariable ["cti_town_neighbors", [Sinai,Resafa,Airport]];
		Industrial_Park setVariable ["cti_town_neighbors", [Sinai,Askari,Highway11,Airport]];
		Highway11 setVariable ["cti_town_neighbors", [FOB,Airport,Industrial_Park]];
		Airport setVariable ["cti_town_neighbors", [Fallujah_Barrage,Industrial_Park, Highway11]];
	};
	case "noe": {
		Kvilda setVariable ["cti_town_neighbors", [IslandAirfield,Loukov,Trosky,ComPlatform]];
		IslandAirfield setVariable ["cti_town_neighbors", [Kvilda,OilRig]];
		Loukov setVariable ["cti_town_neighbors", [Kvilda,Trosky,Bitov,Blata,ComPlatform]];
		Bitov setVariable ["cti_town_neighbors", [VelkaVes,Loukov,Lipany,Blata,RadarPlatform]];
		Lipany setVariable ["cti_town_neighbors", [Bitov,VelkaVes,StSedlo,Bor,RadarPlatform]];
		StSedlo setVariable ["cti_town_neighbors", [Lipany,USSWasp,Bor]];
		USSWasp setVariable ["cti_town_neighbors", [StSedlo,Vidlakov,ResearchPlatform]];
		VelkaVes setVariable ["cti_town_neighbors", [Bitov,Lipany,Joudov,Neveklov,Blata]];
		Trosky setVariable ["cti_town_neighbors", [Mokropsy,Loukov,Kvilda,Joudov,Blata]];
		Joudov setVariable ["cti_town_neighbors", [Mokropsy,Neveklov,Trosky,VelkaVes,Mirov]];
		MokraVrata setVariable ["cti_town_neighbors", [OilRig,Modrava]];
		Modrava setVariable ["cti_town_neighbors", [MokraVrata,Mokropsy,Mirov,Hill19]];
		Mirov setVariable ["cti_town_neighbors", [Mirov,Modrava,Petrovice,WestAirfield,Joudov]];
		WestAirfield setVariable ["cti_town_neighbors", [Mirov,Petrovice,ResearchPlatform,Hill19]];
		Petrovice setVariable ["cti_town_neighbors", [Vidlakov,WestAirfield,Neveklov,Mirov]];
		Vidlakov setVariable ["cti_town_neighbors", [Petrovice,Neveklov,USSWasp,ResearchPlatform]];
		Neveklov setVariable ["cti_town_neighbors", [Vidlakov,Joudov,VelkaVes,Petrovice]];
		Mokropsy setVariable ["cti_town_neighbors", [Joudov,Trosky,Modrava]];
		ComPlatform setVariable ["cti_town_neighbors", [Loukov,Kvilda,RadarPlatform]];
		OilRig setVariable ["cti_town_neighbors", [IslandAirfield,MokraVrata]];
		Blata setVariable ["cti_town_neighbors", [Loukov,VelkaVes,Trosky,Bitov]];
		Bor setVariable ["cti_town_neighbors", [StSedlo,Lipany]];
		ResearchPlatform setVariable ["cti_town_neighbors", [WestAirfield,USSWasp,Vidlakov]];
		Hill19 setVariable ["cti_town_neighbors", [Modrava,WestAirfield]];
		RadarPlatform setVariable ["cti_town_neighbors", [ComPlatform,Lipany,Bitov]];
	};
	case "hellanmaa": {
		Heikkola setVariable ["cti_town_neighbors", [Koivikko,Rautakorpi,Jussila]];
		Koivikko setVariable ["cti_town_neighbors", [Heikkola,Somppi,Villa,Luoma,Hill58]];
		Rautakorpi setVariable ["cti_town_neighbors", [Heikkola,NorthwestFarm]];
		NorthwestFarm setVariable ["cti_town_neighbors", [Rautakorpi,Kokkila,Hill58]];
		Somppi setVariable ["cti_town_neighbors", [Kokkila,Koivikko,Villa,Hoeoepakka]];
		Villa setVariable ["cti_town_neighbors", [Somppi,Luoma,Koivikko,FurFarm]];
		Luoma setVariable ["cti_town_neighbors", [Villa,Koivikko,Jussila]];
		Jussila setVariable ["cti_town_neighbors", [Luoma,Heikkola,Taipale]];
		FurFarm setVariable ["cti_town_neighbors", [Villa,Taipale,Garage]];
		Garage setVariable ["cti_town_neighbors", [Hoeoepakka,FurFarm,Huhtala]];
		Hoeoepakka setVariable ["cti_town_neighbors", [Garage,Nyman,Somppi,Juusola]];
		Nyman setVariable ["cti_town_neighbors", [Hoeoepakka,Troihari,AbandonedWarehouse]];
		Troihari setVariable ["cti_town_neighbors", [Kokkila,SouthwestCompany,Nyman]];
		SouthwestCompany setVariable ["cti_town_neighbors", [Troihari,AbandonedWarehouse]];
		AbandonedWarehouse setVariable ["cti_town_neighbors", [SouthwestCompany,Nyman,Kettula,Juusola]];
		Kettula setVariable ["cti_town_neighbors", [AbandonedWarehouse,Juusola,SoutheastFarm]];
		SoutheastFarm setVariable ["cti_town_neighbors", [Kettula,Huhtala,Juusola]];
		Huhtala setVariable ["cti_town_neighbors", [SoutheastFarm,Juusola,Garage,Kontio]];
		Juusola setVariable ["cti_town_neighbors", [Huhtala,SoutheastFarm,Hoeoepakka,Kettula,AbandonedWarehouse]];
		Kontio setVariable ["cti_town_neighbors", [Huhtala,Taipale]];
		Taipale setVariable ["cti_town_neighbors", [Kontio,FurFarm,Jussila]];
		Kokkila setVariable ["cti_town_neighbors", [Troihari,Somppi,NorthwestFarm]];
		Hill58 setVariable ["cti_town_neighbors", [Koivikko,NorthwestFarm]];
	};
};